// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: acquisition.proto

#include "acquisition.pb.h"
#include "acquisition.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace openpni {
namespace distributed {
namespace acquisition {

static const char* AcquisitionControlService_method_names[] = {
  "/openpni.distributed.acquisition.AcquisitionControlService/Connect",
};

std::unique_ptr< AcquisitionControlService::Stub> AcquisitionControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AcquisitionControlService::Stub> stub(new AcquisitionControlService::Stub(channel));
  return stub;
}

AcquisitionControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Connect_(AcquisitionControlService_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>* AcquisitionControlService::Stub::ConnectRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>::Create(channel_.get(), rpcmethod_Connect_, context);
}

void AcquisitionControlService::Stub::experimental_async::Connect(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::openpni::distributed::acquisition::NodeStatus,::openpni::distributed::acquisition::MasterCommand>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::openpni::distributed::acquisition::NodeStatus,::openpni::distributed::acquisition::MasterCommand>::Create(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>* AcquisitionControlService::Stub::AsyncConnectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>::Create(channel_.get(), cq, rpcmethod_Connect_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>* AcquisitionControlService::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>::Create(channel_.get(), cq, rpcmethod_Connect_, context, false, nullptr);
}

AcquisitionControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AcquisitionControlService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AcquisitionControlService::Service, ::openpni::distributed::acquisition::NodeStatus, ::openpni::distributed::acquisition::MasterCommand>(
          [](AcquisitionControlService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::openpni::distributed::acquisition::MasterCommand,
             ::openpni::distributed::acquisition::NodeStatus>* stream) {
               return service->Connect(ctx, stream);
             }, this)));
}

AcquisitionControlService::Service::~Service() {
}

::grpc::Status AcquisitionControlService::Service::Connect(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::openpni::distributed::acquisition::MasterCommand, ::openpni::distributed::acquisition::NodeStatus>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace openpni
}  // namespace distributed
}  // namespace acquisition

