// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acquisition.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_acquisition_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_acquisition_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_acquisition_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_acquisition_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_acquisition_2eproto;
namespace openpni {
namespace distributed {
namespace acquisition {
class AcquisitionTask;
class AcquisitionTaskDefaultTypeInternal;
extern AcquisitionTaskDefaultTypeInternal _AcquisitionTask_default_instance_;
class ChannelConfig;
class ChannelConfigDefaultTypeInternal;
extern ChannelConfigDefaultTypeInternal _ChannelConfig_default_instance_;
class MasterCommand;
class MasterCommandDefaultTypeInternal;
extern MasterCommandDefaultTypeInternal _MasterCommand_default_instance_;
class NodeInfo;
class NodeInfoDefaultTypeInternal;
extern NodeInfoDefaultTypeInternal _NodeInfo_default_instance_;
class NodeStatus;
class NodeStatusDefaultTypeInternal;
extern NodeStatusDefaultTypeInternal _NodeStatus_default_instance_;
}  // namespace acquisition
}  // namespace distributed
}  // namespace openpni
PROTOBUF_NAMESPACE_OPEN
template<> ::openpni::distributed::acquisition::AcquisitionTask* Arena::CreateMaybeMessage<::openpni::distributed::acquisition::AcquisitionTask>(Arena*);
template<> ::openpni::distributed::acquisition::ChannelConfig* Arena::CreateMaybeMessage<::openpni::distributed::acquisition::ChannelConfig>(Arena*);
template<> ::openpni::distributed::acquisition::MasterCommand* Arena::CreateMaybeMessage<::openpni::distributed::acquisition::MasterCommand>(Arena*);
template<> ::openpni::distributed::acquisition::NodeInfo* Arena::CreateMaybeMessage<::openpni::distributed::acquisition::NodeInfo>(Arena*);
template<> ::openpni::distributed::acquisition::NodeStatus* Arena::CreateMaybeMessage<::openpni::distributed::acquisition::NodeStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace openpni {
namespace distributed {
namespace acquisition {

enum CommandType : int {
  CMD_UNKNOWN = 0,
  CMD_CONFIGURE = 1,
  CMD_START = 2,
  CMD_STOP = 3,
  CMD_SHUTDOWN = 4,
  CommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CommandType_IsValid(int value);
constexpr CommandType CommandType_MIN = CMD_UNKNOWN;
constexpr CommandType CommandType_MAX = CMD_SHUTDOWN;
constexpr int CommandType_ARRAYSIZE = CommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandType_descriptor();
template<typename T>
inline const std::string& CommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CommandType_descriptor(), enum_t_value);
}
inline bool CommandType_Parse(
    const std::string& name, CommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CommandType>(
    CommandType_descriptor(), name, value);
}
enum NodeState : int {
  STATE_UNKNOWN = 0,
  STATE_IDLE = 1,
  STATE_CONFIGURED = 2,
  STATE_RUNNING = 3,
  STATE_ERROR = 4,
  NodeState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  NodeState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool NodeState_IsValid(int value);
constexpr NodeState NodeState_MIN = STATE_UNKNOWN;
constexpr NodeState NodeState_MAX = STATE_ERROR;
constexpr int NodeState_ARRAYSIZE = NodeState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NodeState_descriptor();
template<typename T>
inline const std::string& NodeState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, NodeState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function NodeState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    NodeState_descriptor(), enum_t_value);
}
inline bool NodeState_Parse(
    const std::string& name, NodeState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<NodeState>(
    NodeState_descriptor(), name, value);
}
// ===================================================================

class ChannelConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.acquisition.ChannelConfig) */ {
 public:
  inline ChannelConfig() : ChannelConfig(nullptr) {};
  virtual ~ChannelConfig();

  ChannelConfig(const ChannelConfig& from);
  ChannelConfig(ChannelConfig&& from) noexcept
    : ChannelConfig() {
    *this = ::std::move(from);
  }

  inline ChannelConfig& operator=(const ChannelConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChannelConfig& operator=(ChannelConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ChannelConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChannelConfig* internal_default_instance() {
    return reinterpret_cast<const ChannelConfig*>(
               &_ChannelConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChannelConfig& a, ChannelConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(ChannelConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChannelConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ChannelConfig* New() const final {
    return CreateMaybeMessage<ChannelConfig>(nullptr);
  }

  ChannelConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ChannelConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ChannelConfig& from);
  void MergeFrom(const ChannelConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChannelConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.acquisition.ChannelConfig";
  }
  protected:
  explicit ChannelConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_acquisition_2eproto);
    return ::descriptor_table_acquisition_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpSourceFieldNumber = 1,
    kPortSourceFieldNumber = 2,
    kIpDestinationFieldNumber = 3,
    kPortDestinationFieldNumber = 4,
    kChannelIndexFieldNumber = 5,
  };
  // uint32 ip_source = 1;
  void clear_ip_source();
  ::PROTOBUF_NAMESPACE_ID::uint32 ip_source() const;
  void set_ip_source(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ip_source() const;
  void _internal_set_ip_source(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 port_source = 2;
  void clear_port_source();
  ::PROTOBUF_NAMESPACE_ID::uint32 port_source() const;
  void set_port_source(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_port_source() const;
  void _internal_set_port_source(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 ip_destination = 3;
  void clear_ip_destination();
  ::PROTOBUF_NAMESPACE_ID::uint32 ip_destination() const;
  void set_ip_destination(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ip_destination() const;
  void _internal_set_ip_destination(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 port_destination = 4;
  void clear_port_destination();
  ::PROTOBUF_NAMESPACE_ID::uint32 port_destination() const;
  void set_port_destination(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_port_destination() const;
  void _internal_set_port_destination(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 channel_index = 5;
  void clear_channel_index();
  ::PROTOBUF_NAMESPACE_ID::uint32 channel_index() const;
  void set_channel_index(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_channel_index() const;
  void _internal_set_channel_index(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.acquisition.ChannelConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ip_source_;
  ::PROTOBUF_NAMESPACE_ID::uint32 port_source_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ip_destination_;
  ::PROTOBUF_NAMESPACE_ID::uint32 port_destination_;
  ::PROTOBUF_NAMESPACE_ID::uint32 channel_index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_acquisition_2eproto;
};
// -------------------------------------------------------------------

class AcquisitionTask PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.acquisition.AcquisitionTask) */ {
 public:
  inline AcquisitionTask() : AcquisitionTask(nullptr) {};
  virtual ~AcquisitionTask();

  AcquisitionTask(const AcquisitionTask& from);
  AcquisitionTask(AcquisitionTask&& from) noexcept
    : AcquisitionTask() {
    *this = ::std::move(from);
  }

  inline AcquisitionTask& operator=(const AcquisitionTask& from) {
    CopyFrom(from);
    return *this;
  }
  inline AcquisitionTask& operator=(AcquisitionTask&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AcquisitionTask& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AcquisitionTask* internal_default_instance() {
    return reinterpret_cast<const AcquisitionTask*>(
               &_AcquisitionTask_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AcquisitionTask& a, AcquisitionTask& b) {
    a.Swap(&b);
  }
  inline void Swap(AcquisitionTask* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AcquisitionTask* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AcquisitionTask* New() const final {
    return CreateMaybeMessage<AcquisitionTask>(nullptr);
  }

  AcquisitionTask* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AcquisitionTask>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AcquisitionTask& from);
  void MergeFrom(const AcquisitionTask& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AcquisitionTask* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.acquisition.AcquisitionTask";
  }
  protected:
  explicit AcquisitionTask(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_acquisition_2eproto);
    return ::descriptor_table_acquisition_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChannelsFieldNumber = 5,
    kMaxBufferSizeFieldNumber = 2,
    kStorageUnitSizeFieldNumber = 1,
    kTimeSwitchBufferMsFieldNumber = 3,
    kTotalChannelNumFieldNumber = 4,
    kMinPacketSizeFieldNumber = 6,
  };
  // repeated .openpni.distributed.acquisition.ChannelConfig channels = 5;
  int channels_size() const;
  private:
  int _internal_channels_size() const;
  public:
  void clear_channels();
  ::openpni::distributed::acquisition::ChannelConfig* mutable_channels(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::acquisition::ChannelConfig >*
      mutable_channels();
  private:
  const ::openpni::distributed::acquisition::ChannelConfig& _internal_channels(int index) const;
  ::openpni::distributed::acquisition::ChannelConfig* _internal_add_channels();
  public:
  const ::openpni::distributed::acquisition::ChannelConfig& channels(int index) const;
  ::openpni::distributed::acquisition::ChannelConfig* add_channels();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::acquisition::ChannelConfig >&
      channels() const;

  // uint64 max_buffer_size = 2;
  void clear_max_buffer_size();
  ::PROTOBUF_NAMESPACE_ID::uint64 max_buffer_size() const;
  void set_max_buffer_size(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_max_buffer_size() const;
  void _internal_set_max_buffer_size(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 storage_unit_size = 1;
  void clear_storage_unit_size();
  ::PROTOBUF_NAMESPACE_ID::uint32 storage_unit_size() const;
  void set_storage_unit_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_storage_unit_size() const;
  void _internal_set_storage_unit_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 time_switch_buffer_ms = 3;
  void clear_time_switch_buffer_ms();
  ::PROTOBUF_NAMESPACE_ID::uint32 time_switch_buffer_ms() const;
  void set_time_switch_buffer_ms(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_time_switch_buffer_ms() const;
  void _internal_set_time_switch_buffer_ms(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 total_channel_num = 4;
  void clear_total_channel_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 total_channel_num() const;
  void set_total_channel_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_total_channel_num() const;
  void _internal_set_total_channel_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 min_packet_size = 6;
  void clear_min_packet_size();
  ::PROTOBUF_NAMESPACE_ID::uint32 min_packet_size() const;
  void set_min_packet_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_min_packet_size() const;
  void _internal_set_min_packet_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.acquisition.AcquisitionTask)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::acquisition::ChannelConfig > channels_;
  ::PROTOBUF_NAMESPACE_ID::uint64 max_buffer_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 storage_unit_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 time_switch_buffer_ms_;
  ::PROTOBUF_NAMESPACE_ID::uint32 total_channel_num_;
  ::PROTOBUF_NAMESPACE_ID::uint32 min_packet_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_acquisition_2eproto;
};
// -------------------------------------------------------------------

class NodeInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.acquisition.NodeInfo) */ {
 public:
  inline NodeInfo() : NodeInfo(nullptr) {};
  virtual ~NodeInfo();

  NodeInfo(const NodeInfo& from);
  NodeInfo(NodeInfo&& from) noexcept
    : NodeInfo() {
    *this = ::std::move(from);
  }

  inline NodeInfo& operator=(const NodeInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeInfo& operator=(NodeInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NodeInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NodeInfo* internal_default_instance() {
    return reinterpret_cast<const NodeInfo*>(
               &_NodeInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NodeInfo& a, NodeInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NodeInfo* New() const final {
    return CreateMaybeMessage<NodeInfo>(nullptr);
  }

  NodeInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NodeInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NodeInfo& from);
  void MergeFrom(const NodeInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.acquisition.NodeInfo";
  }
  protected:
  explicit NodeInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_acquisition_2eproto);
    return ::descriptor_table_acquisition_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kHostnameFieldNumber = 2,
    kIpAddressFieldNumber = 3,
    kMemorySizeFieldNumber = 5,
    kCpuCoresFieldNumber = 4,
  };
  // string node_id = 1;
  void clear_node_id();
  const std::string& node_id() const;
  void set_node_id(const std::string& value);
  void set_node_id(std::string&& value);
  void set_node_id(const char* value);
  void set_node_id(const char* value, size_t size);
  std::string* mutable_node_id();
  std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_node_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_node_id(
      std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // string hostname = 2;
  void clear_hostname();
  const std::string& hostname() const;
  void set_hostname(const std::string& value);
  void set_hostname(std::string&& value);
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  std::string* mutable_hostname();
  std::string* release_hostname();
  void set_allocated_hostname(std::string* hostname);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_hostname();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_hostname(
      std::string* hostname);
  private:
  const std::string& _internal_hostname() const;
  void _internal_set_hostname(const std::string& value);
  std::string* _internal_mutable_hostname();
  public:

  // string ip_address = 3;
  void clear_ip_address();
  const std::string& ip_address() const;
  void set_ip_address(const std::string& value);
  void set_ip_address(std::string&& value);
  void set_ip_address(const char* value);
  void set_ip_address(const char* value, size_t size);
  std::string* mutable_ip_address();
  std::string* release_ip_address();
  void set_allocated_ip_address(std::string* ip_address);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_ip_address();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_ip_address(
      std::string* ip_address);
  private:
  const std::string& _internal_ip_address() const;
  void _internal_set_ip_address(const std::string& value);
  std::string* _internal_mutable_ip_address();
  public:

  // uint64 memory_size = 5;
  void clear_memory_size();
  ::PROTOBUF_NAMESPACE_ID::uint64 memory_size() const;
  void set_memory_size(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_memory_size() const;
  void _internal_set_memory_size(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 cpu_cores = 4;
  void clear_cpu_cores();
  ::PROTOBUF_NAMESPACE_ID::uint32 cpu_cores() const;
  void set_cpu_cores(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cpu_cores() const;
  void _internal_set_cpu_cores(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.acquisition.NodeInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hostname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_address_;
  ::PROTOBUF_NAMESPACE_ID::uint64 memory_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cpu_cores_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_acquisition_2eproto;
};
// -------------------------------------------------------------------

class MasterCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.acquisition.MasterCommand) */ {
 public:
  inline MasterCommand() : MasterCommand(nullptr) {};
  virtual ~MasterCommand();

  MasterCommand(const MasterCommand& from);
  MasterCommand(MasterCommand&& from) noexcept
    : MasterCommand() {
    *this = ::std::move(from);
  }

  inline MasterCommand& operator=(const MasterCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline MasterCommand& operator=(MasterCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MasterCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MasterCommand* internal_default_instance() {
    return reinterpret_cast<const MasterCommand*>(
               &_MasterCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MasterCommand& a, MasterCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(MasterCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MasterCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MasterCommand* New() const final {
    return CreateMaybeMessage<MasterCommand>(nullptr);
  }

  MasterCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MasterCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MasterCommand& from);
  void MergeFrom(const MasterCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MasterCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.acquisition.MasterCommand";
  }
  protected:
  explicit MasterCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_acquisition_2eproto);
    return ::descriptor_table_acquisition_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 3,
    kTaskFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // string message = 3;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .openpni.distributed.acquisition.AcquisitionTask task = 2;
  bool has_task() const;
  private:
  bool _internal_has_task() const;
  public:
  void clear_task();
  const ::openpni::distributed::acquisition::AcquisitionTask& task() const;
  ::openpni::distributed::acquisition::AcquisitionTask* release_task();
  ::openpni::distributed::acquisition::AcquisitionTask* mutable_task();
  void set_allocated_task(::openpni::distributed::acquisition::AcquisitionTask* task);
  private:
  const ::openpni::distributed::acquisition::AcquisitionTask& _internal_task() const;
  ::openpni::distributed::acquisition::AcquisitionTask* _internal_mutable_task();
  public:
  void unsafe_arena_set_allocated_task(
      ::openpni::distributed::acquisition::AcquisitionTask* task);
  ::openpni::distributed::acquisition::AcquisitionTask* unsafe_arena_release_task();

  // .openpni.distributed.acquisition.CommandType type = 1;
  void clear_type();
  ::openpni::distributed::acquisition::CommandType type() const;
  void set_type(::openpni::distributed::acquisition::CommandType value);
  private:
  ::openpni::distributed::acquisition::CommandType _internal_type() const;
  void _internal_set_type(::openpni::distributed::acquisition::CommandType value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.acquisition.MasterCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::openpni::distributed::acquisition::AcquisitionTask* task_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_acquisition_2eproto;
};
// -------------------------------------------------------------------

class NodeStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.acquisition.NodeStatus) */ {
 public:
  inline NodeStatus() : NodeStatus(nullptr) {};
  virtual ~NodeStatus();

  NodeStatus(const NodeStatus& from);
  NodeStatus(NodeStatus&& from) noexcept
    : NodeStatus() {
    *this = ::std::move(from);
  }

  inline NodeStatus& operator=(const NodeStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeStatus& operator=(NodeStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NodeStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NodeStatus* internal_default_instance() {
    return reinterpret_cast<const NodeStatus*>(
               &_NodeStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(NodeStatus& a, NodeStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NodeStatus* New() const final {
    return CreateMaybeMessage<NodeStatus>(nullptr);
  }

  NodeStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NodeStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NodeStatus& from);
  void MergeFrom(const NodeStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.acquisition.NodeStatus";
  }
  protected:
  explicit NodeStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_acquisition_2eproto);
    return ::descriptor_table_acquisition_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 3,
    kInfoFieldNumber = 1,
    kCurrentSpeedMppsFieldNumber = 4,
    kCurrentBandwidthMbpsFieldNumber = 5,
    kStateFieldNumber = 2,
  };
  // string error_message = 3;
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // .openpni.distributed.acquisition.NodeInfo info = 1;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const ::openpni::distributed::acquisition::NodeInfo& info() const;
  ::openpni::distributed::acquisition::NodeInfo* release_info();
  ::openpni::distributed::acquisition::NodeInfo* mutable_info();
  void set_allocated_info(::openpni::distributed::acquisition::NodeInfo* info);
  private:
  const ::openpni::distributed::acquisition::NodeInfo& _internal_info() const;
  ::openpni::distributed::acquisition::NodeInfo* _internal_mutable_info();
  public:
  void unsafe_arena_set_allocated_info(
      ::openpni::distributed::acquisition::NodeInfo* info);
  ::openpni::distributed::acquisition::NodeInfo* unsafe_arena_release_info();

  // double current_speed_mpps = 4;
  void clear_current_speed_mpps();
  double current_speed_mpps() const;
  void set_current_speed_mpps(double value);
  private:
  double _internal_current_speed_mpps() const;
  void _internal_set_current_speed_mpps(double value);
  public:

  // double current_bandwidth_mbps = 5;
  void clear_current_bandwidth_mbps();
  double current_bandwidth_mbps() const;
  void set_current_bandwidth_mbps(double value);
  private:
  double _internal_current_bandwidth_mbps() const;
  void _internal_set_current_bandwidth_mbps(double value);
  public:

  // .openpni.distributed.acquisition.NodeState state = 2;
  void clear_state();
  ::openpni::distributed::acquisition::NodeState state() const;
  void set_state(::openpni::distributed::acquisition::NodeState value);
  private:
  ::openpni::distributed::acquisition::NodeState _internal_state() const;
  void _internal_set_state(::openpni::distributed::acquisition::NodeState value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.acquisition.NodeStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  ::openpni::distributed::acquisition::NodeInfo* info_;
  double current_speed_mpps_;
  double current_bandwidth_mbps_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_acquisition_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChannelConfig

// uint32 ip_source = 1;
inline void ChannelConfig::clear_ip_source() {
  ip_source_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::_internal_ip_source() const {
  return ip_source_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::ip_source() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.ChannelConfig.ip_source)
  return _internal_ip_source();
}
inline void ChannelConfig::_internal_set_ip_source(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  ip_source_ = value;
}
inline void ChannelConfig::set_ip_source(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ip_source(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.ChannelConfig.ip_source)
}

// uint32 port_source = 2;
inline void ChannelConfig::clear_port_source() {
  port_source_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::_internal_port_source() const {
  return port_source_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::port_source() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.ChannelConfig.port_source)
  return _internal_port_source();
}
inline void ChannelConfig::_internal_set_port_source(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  port_source_ = value;
}
inline void ChannelConfig::set_port_source(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_port_source(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.ChannelConfig.port_source)
}

// uint32 ip_destination = 3;
inline void ChannelConfig::clear_ip_destination() {
  ip_destination_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::_internal_ip_destination() const {
  return ip_destination_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::ip_destination() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.ChannelConfig.ip_destination)
  return _internal_ip_destination();
}
inline void ChannelConfig::_internal_set_ip_destination(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  ip_destination_ = value;
}
inline void ChannelConfig::set_ip_destination(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ip_destination(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.ChannelConfig.ip_destination)
}

// uint32 port_destination = 4;
inline void ChannelConfig::clear_port_destination() {
  port_destination_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::_internal_port_destination() const {
  return port_destination_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::port_destination() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.ChannelConfig.port_destination)
  return _internal_port_destination();
}
inline void ChannelConfig::_internal_set_port_destination(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  port_destination_ = value;
}
inline void ChannelConfig::set_port_destination(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_port_destination(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.ChannelConfig.port_destination)
}

// uint32 channel_index = 5;
inline void ChannelConfig::clear_channel_index() {
  channel_index_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::_internal_channel_index() const {
  return channel_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ChannelConfig::channel_index() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.ChannelConfig.channel_index)
  return _internal_channel_index();
}
inline void ChannelConfig::_internal_set_channel_index(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  channel_index_ = value;
}
inline void ChannelConfig::set_channel_index(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_channel_index(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.ChannelConfig.channel_index)
}

// -------------------------------------------------------------------

// AcquisitionTask

// uint32 storage_unit_size = 1;
inline void AcquisitionTask::clear_storage_unit_size() {
  storage_unit_size_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::_internal_storage_unit_size() const {
  return storage_unit_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::storage_unit_size() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.AcquisitionTask.storage_unit_size)
  return _internal_storage_unit_size();
}
inline void AcquisitionTask::_internal_set_storage_unit_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  storage_unit_size_ = value;
}
inline void AcquisitionTask::set_storage_unit_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_storage_unit_size(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.AcquisitionTask.storage_unit_size)
}

// uint64 max_buffer_size = 2;
inline void AcquisitionTask::clear_max_buffer_size() {
  max_buffer_size_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AcquisitionTask::_internal_max_buffer_size() const {
  return max_buffer_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AcquisitionTask::max_buffer_size() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.AcquisitionTask.max_buffer_size)
  return _internal_max_buffer_size();
}
inline void AcquisitionTask::_internal_set_max_buffer_size(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  max_buffer_size_ = value;
}
inline void AcquisitionTask::set_max_buffer_size(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_max_buffer_size(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.AcquisitionTask.max_buffer_size)
}

// uint32 time_switch_buffer_ms = 3;
inline void AcquisitionTask::clear_time_switch_buffer_ms() {
  time_switch_buffer_ms_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::_internal_time_switch_buffer_ms() const {
  return time_switch_buffer_ms_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::time_switch_buffer_ms() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.AcquisitionTask.time_switch_buffer_ms)
  return _internal_time_switch_buffer_ms();
}
inline void AcquisitionTask::_internal_set_time_switch_buffer_ms(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  time_switch_buffer_ms_ = value;
}
inline void AcquisitionTask::set_time_switch_buffer_ms(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_time_switch_buffer_ms(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.AcquisitionTask.time_switch_buffer_ms)
}

// uint32 total_channel_num = 4;
inline void AcquisitionTask::clear_total_channel_num() {
  total_channel_num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::_internal_total_channel_num() const {
  return total_channel_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::total_channel_num() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.AcquisitionTask.total_channel_num)
  return _internal_total_channel_num();
}
inline void AcquisitionTask::_internal_set_total_channel_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  total_channel_num_ = value;
}
inline void AcquisitionTask::set_total_channel_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_total_channel_num(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.AcquisitionTask.total_channel_num)
}

// uint32 min_packet_size = 6;
inline void AcquisitionTask::clear_min_packet_size() {
  min_packet_size_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::_internal_min_packet_size() const {
  return min_packet_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 AcquisitionTask::min_packet_size() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.AcquisitionTask.min_packet_size)
  return _internal_min_packet_size();
}
inline void AcquisitionTask::_internal_set_min_packet_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  min_packet_size_ = value;
}
inline void AcquisitionTask::set_min_packet_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_min_packet_size(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.AcquisitionTask.min_packet_size)
}

// repeated .openpni.distributed.acquisition.ChannelConfig channels = 5;
inline int AcquisitionTask::_internal_channels_size() const {
  return channels_.size();
}
inline int AcquisitionTask::channels_size() const {
  return _internal_channels_size();
}
inline void AcquisitionTask::clear_channels() {
  channels_.Clear();
}
inline ::openpni::distributed::acquisition::ChannelConfig* AcquisitionTask::mutable_channels(int index) {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.AcquisitionTask.channels)
  return channels_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::acquisition::ChannelConfig >*
AcquisitionTask::mutable_channels() {
  // @@protoc_insertion_point(field_mutable_list:openpni.distributed.acquisition.AcquisitionTask.channels)
  return &channels_;
}
inline const ::openpni::distributed::acquisition::ChannelConfig& AcquisitionTask::_internal_channels(int index) const {
  return channels_.Get(index);
}
inline const ::openpni::distributed::acquisition::ChannelConfig& AcquisitionTask::channels(int index) const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.AcquisitionTask.channels)
  return _internal_channels(index);
}
inline ::openpni::distributed::acquisition::ChannelConfig* AcquisitionTask::_internal_add_channels() {
  return channels_.Add();
}
inline ::openpni::distributed::acquisition::ChannelConfig* AcquisitionTask::add_channels() {
  // @@protoc_insertion_point(field_add:openpni.distributed.acquisition.AcquisitionTask.channels)
  return _internal_add_channels();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::acquisition::ChannelConfig >&
AcquisitionTask::channels() const {
  // @@protoc_insertion_point(field_list:openpni.distributed.acquisition.AcquisitionTask.channels)
  return channels_;
}

// -------------------------------------------------------------------

// NodeInfo

// string node_id = 1;
inline void NodeInfo::clear_node_id() {
  node_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NodeInfo::node_id() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeInfo.node_id)
  return _internal_node_id();
}
inline void NodeInfo::set_node_id(const std::string& value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeInfo.node_id)
}
inline std::string* NodeInfo::mutable_node_id() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.NodeInfo.node_id)
  return _internal_mutable_node_id();
}
inline const std::string& NodeInfo::_internal_node_id() const {
  return node_id_.Get();
}
inline void NodeInfo::_internal_set_node_id(const std::string& value) {
  
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NodeInfo::set_node_id(std::string&& value) {
  
  node_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.acquisition.NodeInfo.node_id)
}
inline void NodeInfo::set_node_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.acquisition.NodeInfo.node_id)
}
inline void NodeInfo::set_node_id(const char* value,
    size_t size) {
  
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.acquisition.NodeInfo.node_id)
}
inline std::string* NodeInfo::_internal_mutable_node_id() {
  
  return node_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NodeInfo::release_node_id() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.NodeInfo.node_id)
  return node_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NodeInfo::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  node_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), node_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.NodeInfo.node_id)
}
inline std::string* NodeInfo::unsafe_arena_release_node_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.acquisition.NodeInfo.node_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return node_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void NodeInfo::unsafe_arena_set_allocated_node_id(
    std::string* node_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (node_id != nullptr) {
    
  } else {
    
  }
  node_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      node_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.NodeInfo.node_id)
}

// string hostname = 2;
inline void NodeInfo::clear_hostname() {
  hostname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NodeInfo::hostname() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeInfo.hostname)
  return _internal_hostname();
}
inline void NodeInfo::set_hostname(const std::string& value) {
  _internal_set_hostname(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeInfo.hostname)
}
inline std::string* NodeInfo::mutable_hostname() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.NodeInfo.hostname)
  return _internal_mutable_hostname();
}
inline const std::string& NodeInfo::_internal_hostname() const {
  return hostname_.Get();
}
inline void NodeInfo::_internal_set_hostname(const std::string& value) {
  
  hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NodeInfo::set_hostname(std::string&& value) {
  
  hostname_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.acquisition.NodeInfo.hostname)
}
inline void NodeInfo::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.acquisition.NodeInfo.hostname)
}
inline void NodeInfo::set_hostname(const char* value,
    size_t size) {
  
  hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.acquisition.NodeInfo.hostname)
}
inline std::string* NodeInfo::_internal_mutable_hostname() {
  
  return hostname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NodeInfo::release_hostname() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.NodeInfo.hostname)
  return hostname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NodeInfo::set_allocated_hostname(std::string* hostname) {
  if (hostname != nullptr) {
    
  } else {
    
  }
  hostname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), hostname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.NodeInfo.hostname)
}
inline std::string* NodeInfo::unsafe_arena_release_hostname() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.acquisition.NodeInfo.hostname)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return hostname_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void NodeInfo::unsafe_arena_set_allocated_hostname(
    std::string* hostname) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (hostname != nullptr) {
    
  } else {
    
  }
  hostname_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      hostname, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.NodeInfo.hostname)
}

// string ip_address = 3;
inline void NodeInfo::clear_ip_address() {
  ip_address_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NodeInfo::ip_address() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeInfo.ip_address)
  return _internal_ip_address();
}
inline void NodeInfo::set_ip_address(const std::string& value) {
  _internal_set_ip_address(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeInfo.ip_address)
}
inline std::string* NodeInfo::mutable_ip_address() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.NodeInfo.ip_address)
  return _internal_mutable_ip_address();
}
inline const std::string& NodeInfo::_internal_ip_address() const {
  return ip_address_.Get();
}
inline void NodeInfo::_internal_set_ip_address(const std::string& value) {
  
  ip_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NodeInfo::set_ip_address(std::string&& value) {
  
  ip_address_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.acquisition.NodeInfo.ip_address)
}
inline void NodeInfo::set_ip_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ip_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.acquisition.NodeInfo.ip_address)
}
inline void NodeInfo::set_ip_address(const char* value,
    size_t size) {
  
  ip_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.acquisition.NodeInfo.ip_address)
}
inline std::string* NodeInfo::_internal_mutable_ip_address() {
  
  return ip_address_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NodeInfo::release_ip_address() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.NodeInfo.ip_address)
  return ip_address_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NodeInfo::set_allocated_ip_address(std::string* ip_address) {
  if (ip_address != nullptr) {
    
  } else {
    
  }
  ip_address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip_address,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.NodeInfo.ip_address)
}
inline std::string* NodeInfo::unsafe_arena_release_ip_address() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.acquisition.NodeInfo.ip_address)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return ip_address_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void NodeInfo::unsafe_arena_set_allocated_ip_address(
    std::string* ip_address) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (ip_address != nullptr) {
    
  } else {
    
  }
  ip_address_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ip_address, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.NodeInfo.ip_address)
}

// uint32 cpu_cores = 4;
inline void NodeInfo::clear_cpu_cores() {
  cpu_cores_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NodeInfo::_internal_cpu_cores() const {
  return cpu_cores_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NodeInfo::cpu_cores() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeInfo.cpu_cores)
  return _internal_cpu_cores();
}
inline void NodeInfo::_internal_set_cpu_cores(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cpu_cores_ = value;
}
inline void NodeInfo::set_cpu_cores(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cpu_cores(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeInfo.cpu_cores)
}

// uint64 memory_size = 5;
inline void NodeInfo::clear_memory_size() {
  memory_size_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 NodeInfo::_internal_memory_size() const {
  return memory_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 NodeInfo::memory_size() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeInfo.memory_size)
  return _internal_memory_size();
}
inline void NodeInfo::_internal_set_memory_size(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  memory_size_ = value;
}
inline void NodeInfo::set_memory_size(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_memory_size(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeInfo.memory_size)
}

// -------------------------------------------------------------------

// MasterCommand

// .openpni.distributed.acquisition.CommandType type = 1;
inline void MasterCommand::clear_type() {
  type_ = 0;
}
inline ::openpni::distributed::acquisition::CommandType MasterCommand::_internal_type() const {
  return static_cast< ::openpni::distributed::acquisition::CommandType >(type_);
}
inline ::openpni::distributed::acquisition::CommandType MasterCommand::type() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.MasterCommand.type)
  return _internal_type();
}
inline void MasterCommand::_internal_set_type(::openpni::distributed::acquisition::CommandType value) {
  
  type_ = value;
}
inline void MasterCommand::set_type(::openpni::distributed::acquisition::CommandType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.MasterCommand.type)
}

// .openpni.distributed.acquisition.AcquisitionTask task = 2;
inline bool MasterCommand::_internal_has_task() const {
  return this != internal_default_instance() && task_ != nullptr;
}
inline bool MasterCommand::has_task() const {
  return _internal_has_task();
}
inline void MasterCommand::clear_task() {
  if (GetArena() == nullptr && task_ != nullptr) {
    delete task_;
  }
  task_ = nullptr;
}
inline const ::openpni::distributed::acquisition::AcquisitionTask& MasterCommand::_internal_task() const {
  const ::openpni::distributed::acquisition::AcquisitionTask* p = task_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openpni::distributed::acquisition::AcquisitionTask*>(
      &::openpni::distributed::acquisition::_AcquisitionTask_default_instance_);
}
inline const ::openpni::distributed::acquisition::AcquisitionTask& MasterCommand::task() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.MasterCommand.task)
  return _internal_task();
}
inline void MasterCommand::unsafe_arena_set_allocated_task(
    ::openpni::distributed::acquisition::AcquisitionTask* task) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(task_);
  }
  task_ = task;
  if (task) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.MasterCommand.task)
}
inline ::openpni::distributed::acquisition::AcquisitionTask* MasterCommand::release_task() {
  auto temp = unsafe_arena_release_task();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openpni::distributed::acquisition::AcquisitionTask* MasterCommand::unsafe_arena_release_task() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.MasterCommand.task)
  
  ::openpni::distributed::acquisition::AcquisitionTask* temp = task_;
  task_ = nullptr;
  return temp;
}
inline ::openpni::distributed::acquisition::AcquisitionTask* MasterCommand::_internal_mutable_task() {
  
  if (task_ == nullptr) {
    auto* p = CreateMaybeMessage<::openpni::distributed::acquisition::AcquisitionTask>(GetArena());
    task_ = p;
  }
  return task_;
}
inline ::openpni::distributed::acquisition::AcquisitionTask* MasterCommand::mutable_task() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.MasterCommand.task)
  return _internal_mutable_task();
}
inline void MasterCommand::set_allocated_task(::openpni::distributed::acquisition::AcquisitionTask* task) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete task_;
  }
  if (task) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(task);
    if (message_arena != submessage_arena) {
      task = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, task, submessage_arena);
    }
    
  } else {
    
  }
  task_ = task;
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.MasterCommand.task)
}

// string message = 3;
inline void MasterCommand::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MasterCommand::message() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.MasterCommand.message)
  return _internal_message();
}
inline void MasterCommand::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.MasterCommand.message)
}
inline std::string* MasterCommand::mutable_message() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.MasterCommand.message)
  return _internal_mutable_message();
}
inline const std::string& MasterCommand::_internal_message() const {
  return message_.Get();
}
inline void MasterCommand::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MasterCommand::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.acquisition.MasterCommand.message)
}
inline void MasterCommand::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.acquisition.MasterCommand.message)
}
inline void MasterCommand::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.acquisition.MasterCommand.message)
}
inline std::string* MasterCommand::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MasterCommand::release_message() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.MasterCommand.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MasterCommand::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.MasterCommand.message)
}
inline std::string* MasterCommand::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.acquisition.MasterCommand.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MasterCommand::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.MasterCommand.message)
}

// -------------------------------------------------------------------

// NodeStatus

// .openpni.distributed.acquisition.NodeInfo info = 1;
inline bool NodeStatus::_internal_has_info() const {
  return this != internal_default_instance() && info_ != nullptr;
}
inline bool NodeStatus::has_info() const {
  return _internal_has_info();
}
inline void NodeStatus::clear_info() {
  if (GetArena() == nullptr && info_ != nullptr) {
    delete info_;
  }
  info_ = nullptr;
}
inline const ::openpni::distributed::acquisition::NodeInfo& NodeStatus::_internal_info() const {
  const ::openpni::distributed::acquisition::NodeInfo* p = info_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openpni::distributed::acquisition::NodeInfo*>(
      &::openpni::distributed::acquisition::_NodeInfo_default_instance_);
}
inline const ::openpni::distributed::acquisition::NodeInfo& NodeStatus::info() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeStatus.info)
  return _internal_info();
}
inline void NodeStatus::unsafe_arena_set_allocated_info(
    ::openpni::distributed::acquisition::NodeInfo* info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(info_);
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.NodeStatus.info)
}
inline ::openpni::distributed::acquisition::NodeInfo* NodeStatus::release_info() {
  auto temp = unsafe_arena_release_info();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openpni::distributed::acquisition::NodeInfo* NodeStatus::unsafe_arena_release_info() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.NodeStatus.info)
  
  ::openpni::distributed::acquisition::NodeInfo* temp = info_;
  info_ = nullptr;
  return temp;
}
inline ::openpni::distributed::acquisition::NodeInfo* NodeStatus::_internal_mutable_info() {
  
  if (info_ == nullptr) {
    auto* p = CreateMaybeMessage<::openpni::distributed::acquisition::NodeInfo>(GetArena());
    info_ = p;
  }
  return info_;
}
inline ::openpni::distributed::acquisition::NodeInfo* NodeStatus::mutable_info() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.NodeStatus.info)
  return _internal_mutable_info();
}
inline void NodeStatus::set_allocated_info(::openpni::distributed::acquisition::NodeInfo* info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete info_;
  }
  if (info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(info);
    if (message_arena != submessage_arena) {
      info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  info_ = info;
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.NodeStatus.info)
}

// .openpni.distributed.acquisition.NodeState state = 2;
inline void NodeStatus::clear_state() {
  state_ = 0;
}
inline ::openpni::distributed::acquisition::NodeState NodeStatus::_internal_state() const {
  return static_cast< ::openpni::distributed::acquisition::NodeState >(state_);
}
inline ::openpni::distributed::acquisition::NodeState NodeStatus::state() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeStatus.state)
  return _internal_state();
}
inline void NodeStatus::_internal_set_state(::openpni::distributed::acquisition::NodeState value) {
  
  state_ = value;
}
inline void NodeStatus::set_state(::openpni::distributed::acquisition::NodeState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeStatus.state)
}

// string error_message = 3;
inline void NodeStatus::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NodeStatus::error_message() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeStatus.error_message)
  return _internal_error_message();
}
inline void NodeStatus::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeStatus.error_message)
}
inline std::string* NodeStatus::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.acquisition.NodeStatus.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& NodeStatus::_internal_error_message() const {
  return error_message_.Get();
}
inline void NodeStatus::_internal_set_error_message(const std::string& value) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NodeStatus::set_error_message(std::string&& value) {
  
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.acquisition.NodeStatus.error_message)
}
inline void NodeStatus::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.acquisition.NodeStatus.error_message)
}
inline void NodeStatus::set_error_message(const char* value,
    size_t size) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.acquisition.NodeStatus.error_message)
}
inline std::string* NodeStatus::_internal_mutable_error_message() {
  
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NodeStatus::release_error_message() {
  // @@protoc_insertion_point(field_release:openpni.distributed.acquisition.NodeStatus.error_message)
  return error_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NodeStatus::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.acquisition.NodeStatus.error_message)
}
inline std::string* NodeStatus::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.acquisition.NodeStatus.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void NodeStatus::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.acquisition.NodeStatus.error_message)
}

// double current_speed_mpps = 4;
inline void NodeStatus::clear_current_speed_mpps() {
  current_speed_mpps_ = 0;
}
inline double NodeStatus::_internal_current_speed_mpps() const {
  return current_speed_mpps_;
}
inline double NodeStatus::current_speed_mpps() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeStatus.current_speed_mpps)
  return _internal_current_speed_mpps();
}
inline void NodeStatus::_internal_set_current_speed_mpps(double value) {
  
  current_speed_mpps_ = value;
}
inline void NodeStatus::set_current_speed_mpps(double value) {
  _internal_set_current_speed_mpps(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeStatus.current_speed_mpps)
}

// double current_bandwidth_mbps = 5;
inline void NodeStatus::clear_current_bandwidth_mbps() {
  current_bandwidth_mbps_ = 0;
}
inline double NodeStatus::_internal_current_bandwidth_mbps() const {
  return current_bandwidth_mbps_;
}
inline double NodeStatus::current_bandwidth_mbps() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.acquisition.NodeStatus.current_bandwidth_mbps)
  return _internal_current_bandwidth_mbps();
}
inline void NodeStatus::_internal_set_current_bandwidth_mbps(double value) {
  
  current_bandwidth_mbps_ = value;
}
inline void NodeStatus::set_current_bandwidth_mbps(double value) {
  _internal_set_current_bandwidth_mbps(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.acquisition.NodeStatus.current_bandwidth_mbps)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace acquisition
}  // namespace distributed
}  // namespace openpni

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::openpni::distributed::acquisition::CommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::openpni::distributed::acquisition::CommandType>() {
  return ::openpni::distributed::acquisition::CommandType_descriptor();
}
template <> struct is_proto_enum< ::openpni::distributed::acquisition::NodeState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::openpni::distributed::acquisition::NodeState>() {
  return ::openpni::distributed::acquisition::NodeState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_acquisition_2eproto
