// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acquisition.proto

#include "acquisition.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_acquisition_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AcquisitionTask_acquisition_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_acquisition_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ChannelConfig_acquisition_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_acquisition_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NodeInfo_acquisition_2eproto;
namespace openpni {
namespace distributed {
namespace acquisition {
class ChannelConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ChannelConfig> _instance;
} _ChannelConfig_default_instance_;
class AcquisitionTaskDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AcquisitionTask> _instance;
} _AcquisitionTask_default_instance_;
class NodeInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NodeInfo> _instance;
} _NodeInfo_default_instance_;
class MasterCommandDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MasterCommand> _instance;
} _MasterCommand_default_instance_;
class NodeStatusDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NodeStatus> _instance;
} _NodeStatus_default_instance_;
}  // namespace acquisition
}  // namespace distributed
}  // namespace openpni
static void InitDefaultsscc_info_AcquisitionTask_acquisition_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::acquisition::_AcquisitionTask_default_instance_;
    new (ptr) ::openpni::distributed::acquisition::AcquisitionTask();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::acquisition::AcquisitionTask::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AcquisitionTask_acquisition_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_AcquisitionTask_acquisition_2eproto}, {
      &scc_info_ChannelConfig_acquisition_2eproto.base,}};

static void InitDefaultsscc_info_ChannelConfig_acquisition_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::acquisition::_ChannelConfig_default_instance_;
    new (ptr) ::openpni::distributed::acquisition::ChannelConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::acquisition::ChannelConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ChannelConfig_acquisition_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ChannelConfig_acquisition_2eproto}, {}};

static void InitDefaultsscc_info_MasterCommand_acquisition_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::acquisition::_MasterCommand_default_instance_;
    new (ptr) ::openpni::distributed::acquisition::MasterCommand();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::acquisition::MasterCommand::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MasterCommand_acquisition_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MasterCommand_acquisition_2eproto}, {
      &scc_info_AcquisitionTask_acquisition_2eproto.base,}};

static void InitDefaultsscc_info_NodeInfo_acquisition_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::acquisition::_NodeInfo_default_instance_;
    new (ptr) ::openpni::distributed::acquisition::NodeInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::acquisition::NodeInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NodeInfo_acquisition_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NodeInfo_acquisition_2eproto}, {}};

static void InitDefaultsscc_info_NodeStatus_acquisition_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::acquisition::_NodeStatus_default_instance_;
    new (ptr) ::openpni::distributed::acquisition::NodeStatus();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::acquisition::NodeStatus::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_NodeStatus_acquisition_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_NodeStatus_acquisition_2eproto}, {
      &scc_info_NodeInfo_acquisition_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_acquisition_2eproto[5];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_acquisition_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_acquisition_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_acquisition_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::ChannelConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::ChannelConfig, ip_source_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::ChannelConfig, port_source_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::ChannelConfig, ip_destination_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::ChannelConfig, port_destination_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::ChannelConfig, channel_index_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, storage_unit_size_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, max_buffer_size_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, time_switch_buffer_ms_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, total_channel_num_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, min_packet_size_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::AcquisitionTask, channels_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeInfo, node_id_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeInfo, hostname_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeInfo, ip_address_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeInfo, cpu_cores_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeInfo, memory_size_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::MasterCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::MasterCommand, type_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::MasterCommand, task_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::MasterCommand, message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeStatus, info_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeStatus, state_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeStatus, error_message_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeStatus, current_speed_mpps_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::acquisition::NodeStatus, current_bandwidth_mbps_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::openpni::distributed::acquisition::ChannelConfig)},
  { 10, -1, sizeof(::openpni::distributed::acquisition::AcquisitionTask)},
  { 21, -1, sizeof(::openpni::distributed::acquisition::NodeInfo)},
  { 31, -1, sizeof(::openpni::distributed::acquisition::MasterCommand)},
  { 39, -1, sizeof(::openpni::distributed::acquisition::NodeStatus)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::acquisition::_ChannelConfig_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::acquisition::_AcquisitionTask_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::acquisition::_NodeInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::acquisition::_MasterCommand_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::acquisition::_NodeStatus_default_instance_),
};

const char descriptor_table_protodef_acquisition_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021acquisition.proto\022\037openpni.distributed"
  ".acquisition\"\200\001\n\rChannelConfig\022\021\n\tip_sou"
  "rce\030\001 \001(\r\022\023\n\013port_source\030\002 \001(\r\022\026\n\016ip_des"
  "tination\030\003 \001(\r\022\030\n\020port_destination\030\004 \001(\r"
  "\022\025\n\rchannel_index\030\005 \001(\r\"\332\001\n\017AcquisitionT"
  "ask\022\031\n\021storage_unit_size\030\001 \001(\r\022\027\n\017max_bu"
  "ffer_size\030\002 \001(\004\022\035\n\025time_switch_buffer_ms"
  "\030\003 \001(\r\022\031\n\021total_channel_num\030\004 \001(\r\022\027\n\017min"
  "_packet_size\030\006 \001(\r\022@\n\010channels\030\005 \003(\0132..o"
  "penpni.distributed.acquisition.ChannelCo"
  "nfig\"i\n\010NodeInfo\022\017\n\007node_id\030\001 \001(\t\022\020\n\010hos"
  "tname\030\002 \001(\t\022\022\n\nip_address\030\003 \001(\t\022\021\n\tcpu_c"
  "ores\030\004 \001(\r\022\023\n\013memory_size\030\005 \001(\004\"\234\001\n\rMast"
  "erCommand\022:\n\004type\030\001 \001(\0162,.openpni.distri"
  "buted.acquisition.CommandType\022>\n\004task\030\002 "
  "\001(\01320.openpni.distributed.acquisition.Ac"
  "quisitionTask\022\017\n\007message\030\003 \001(\t\"\323\001\n\nNodeS"
  "tatus\0227\n\004info\030\001 \001(\0132).openpni.distribute"
  "d.acquisition.NodeInfo\0229\n\005state\030\002 \001(\0162*."
  "openpni.distributed.acquisition.NodeStat"
  "e\022\025\n\rerror_message\030\003 \001(\t\022\032\n\022current_spee"
  "d_mpps\030\004 \001(\001\022\036\n\026current_bandwidth_mbps\030\005"
  " \001(\001*`\n\013CommandType\022\017\n\013CMD_UNKNOWN\020\000\022\021\n\r"
  "CMD_CONFIGURE\020\001\022\r\n\tCMD_START\020\002\022\014\n\010CMD_ST"
  "OP\020\003\022\020\n\014CMD_SHUTDOWN\020\004*h\n\tNodeState\022\021\n\rS"
  "TATE_UNKNOWN\020\000\022\016\n\nSTATE_IDLE\020\001\022\024\n\020STATE_"
  "CONFIGURED\020\002\022\021\n\rSTATE_RUNNING\020\003\022\017\n\013STATE"
  "_ERROR\020\0042\207\001\n\031AcquisitionControlService\022j"
  "\n\007Connect\022+.openpni.distributed.acquisit"
  "ion.NodeStatus\032..openpni.distributed.acq"
  "uisition.MasterCommand(\0010\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_acquisition_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_acquisition_2eproto_sccs[5] = {
  &scc_info_AcquisitionTask_acquisition_2eproto.base,
  &scc_info_ChannelConfig_acquisition_2eproto.base,
  &scc_info_MasterCommand_acquisition_2eproto.base,
  &scc_info_NodeInfo_acquisition_2eproto.base,
  &scc_info_NodeStatus_acquisition_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_acquisition_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_acquisition_2eproto = {
  false, false, descriptor_table_protodef_acquisition_2eproto, "acquisition.proto", 1234,
  &descriptor_table_acquisition_2eproto_once, descriptor_table_acquisition_2eproto_sccs, descriptor_table_acquisition_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_acquisition_2eproto::offsets,
  file_level_metadata_acquisition_2eproto, 5, file_level_enum_descriptors_acquisition_2eproto, file_level_service_descriptors_acquisition_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_acquisition_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_acquisition_2eproto)), true);
namespace openpni {
namespace distributed {
namespace acquisition {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_acquisition_2eproto);
  return file_level_enum_descriptors_acquisition_2eproto[0];
}
bool CommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NodeState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_acquisition_2eproto);
  return file_level_enum_descriptors_acquisition_2eproto[1];
}
bool NodeState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ChannelConfig::InitAsDefaultInstance() {
}
class ChannelConfig::_Internal {
 public:
};

ChannelConfig::ChannelConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.acquisition.ChannelConfig)
}
ChannelConfig::ChannelConfig(const ChannelConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&ip_source_, &from.ip_source_,
    static_cast<size_t>(reinterpret_cast<char*>(&channel_index_) -
    reinterpret_cast<char*>(&ip_source_)) + sizeof(channel_index_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.acquisition.ChannelConfig)
}

void ChannelConfig::SharedCtor() {
  ::memset(&ip_source_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&channel_index_) -
      reinterpret_cast<char*>(&ip_source_)) + sizeof(channel_index_));
}

ChannelConfig::~ChannelConfig() {
  // @@protoc_insertion_point(destructor:openpni.distributed.acquisition.ChannelConfig)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ChannelConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ChannelConfig::ArenaDtor(void* object) {
  ChannelConfig* _this = reinterpret_cast< ChannelConfig* >(object);
  (void)_this;
}
void ChannelConfig::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ChannelConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ChannelConfig& ChannelConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ChannelConfig_acquisition_2eproto.base);
  return *internal_default_instance();
}


void ChannelConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.acquisition.ChannelConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&ip_source_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&channel_index_) -
      reinterpret_cast<char*>(&ip_source_)) + sizeof(channel_index_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChannelConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 ip_source = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ip_source_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 port_source = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          port_source_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 ip_destination = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ip_destination_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 port_destination = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          port_destination_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 channel_index = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          channel_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ChannelConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.acquisition.ChannelConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ip_source = 1;
  if (this->ip_source() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_ip_source(), target);
  }

  // uint32 port_source = 2;
  if (this->port_source() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_port_source(), target);
  }

  // uint32 ip_destination = 3;
  if (this->ip_destination() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_ip_destination(), target);
  }

  // uint32 port_destination = 4;
  if (this->port_destination() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_port_destination(), target);
  }

  // uint32 channel_index = 5;
  if (this->channel_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_channel_index(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.acquisition.ChannelConfig)
  return target;
}

size_t ChannelConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.acquisition.ChannelConfig)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 ip_source = 1;
  if (this->ip_source() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_ip_source());
  }

  // uint32 port_source = 2;
  if (this->port_source() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_port_source());
  }

  // uint32 ip_destination = 3;
  if (this->ip_destination() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_ip_destination());
  }

  // uint32 port_destination = 4;
  if (this->port_destination() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_port_destination());
  }

  // uint32 channel_index = 5;
  if (this->channel_index() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_channel_index());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ChannelConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.acquisition.ChannelConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const ChannelConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ChannelConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.acquisition.ChannelConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.acquisition.ChannelConfig)
    MergeFrom(*source);
  }
}

void ChannelConfig::MergeFrom(const ChannelConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.acquisition.ChannelConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ip_source() != 0) {
    _internal_set_ip_source(from._internal_ip_source());
  }
  if (from.port_source() != 0) {
    _internal_set_port_source(from._internal_port_source());
  }
  if (from.ip_destination() != 0) {
    _internal_set_ip_destination(from._internal_ip_destination());
  }
  if (from.port_destination() != 0) {
    _internal_set_port_destination(from._internal_port_destination());
  }
  if (from.channel_index() != 0) {
    _internal_set_channel_index(from._internal_channel_index());
  }
}

void ChannelConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.acquisition.ChannelConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChannelConfig::CopyFrom(const ChannelConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.acquisition.ChannelConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChannelConfig::IsInitialized() const {
  return true;
}

void ChannelConfig::InternalSwap(ChannelConfig* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ChannelConfig, channel_index_)
      + sizeof(ChannelConfig::channel_index_)
      - PROTOBUF_FIELD_OFFSET(ChannelConfig, ip_source_)>(
          reinterpret_cast<char*>(&ip_source_),
          reinterpret_cast<char*>(&other->ip_source_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ChannelConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AcquisitionTask::InitAsDefaultInstance() {
}
class AcquisitionTask::_Internal {
 public:
};

AcquisitionTask::AcquisitionTask(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  channels_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.acquisition.AcquisitionTask)
}
AcquisitionTask::AcquisitionTask(const AcquisitionTask& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      channels_(from.channels_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&max_buffer_size_, &from.max_buffer_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&min_packet_size_) -
    reinterpret_cast<char*>(&max_buffer_size_)) + sizeof(min_packet_size_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.acquisition.AcquisitionTask)
}

void AcquisitionTask::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AcquisitionTask_acquisition_2eproto.base);
  ::memset(&max_buffer_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&min_packet_size_) -
      reinterpret_cast<char*>(&max_buffer_size_)) + sizeof(min_packet_size_));
}

AcquisitionTask::~AcquisitionTask() {
  // @@protoc_insertion_point(destructor:openpni.distributed.acquisition.AcquisitionTask)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AcquisitionTask::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void AcquisitionTask::ArenaDtor(void* object) {
  AcquisitionTask* _this = reinterpret_cast< AcquisitionTask* >(object);
  (void)_this;
}
void AcquisitionTask::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AcquisitionTask::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AcquisitionTask& AcquisitionTask::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AcquisitionTask_acquisition_2eproto.base);
  return *internal_default_instance();
}


void AcquisitionTask::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.acquisition.AcquisitionTask)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  channels_.Clear();
  ::memset(&max_buffer_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&min_packet_size_) -
      reinterpret_cast<char*>(&max_buffer_size_)) + sizeof(min_packet_size_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AcquisitionTask::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 storage_unit_size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          storage_unit_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 max_buffer_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          max_buffer_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 time_switch_buffer_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          time_switch_buffer_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 total_channel_num = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          total_channel_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .openpni.distributed.acquisition.ChannelConfig channels = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_channels(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // uint32 min_packet_size = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          min_packet_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AcquisitionTask::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.acquisition.AcquisitionTask)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 storage_unit_size = 1;
  if (this->storage_unit_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_storage_unit_size(), target);
  }

  // uint64 max_buffer_size = 2;
  if (this->max_buffer_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_max_buffer_size(), target);
  }

  // uint32 time_switch_buffer_ms = 3;
  if (this->time_switch_buffer_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_time_switch_buffer_ms(), target);
  }

  // uint32 total_channel_num = 4;
  if (this->total_channel_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_total_channel_num(), target);
  }

  // repeated .openpni.distributed.acquisition.ChannelConfig channels = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_channels_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_channels(i), target, stream);
  }

  // uint32 min_packet_size = 6;
  if (this->min_packet_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_min_packet_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.acquisition.AcquisitionTask)
  return target;
}

size_t AcquisitionTask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.acquisition.AcquisitionTask)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .openpni.distributed.acquisition.ChannelConfig channels = 5;
  total_size += 1UL * this->_internal_channels_size();
  for (const auto& msg : this->channels_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint64 max_buffer_size = 2;
  if (this->max_buffer_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_max_buffer_size());
  }

  // uint32 storage_unit_size = 1;
  if (this->storage_unit_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_storage_unit_size());
  }

  // uint32 time_switch_buffer_ms = 3;
  if (this->time_switch_buffer_ms() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_time_switch_buffer_ms());
  }

  // uint32 total_channel_num = 4;
  if (this->total_channel_num() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_total_channel_num());
  }

  // uint32 min_packet_size = 6;
  if (this->min_packet_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_min_packet_size());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AcquisitionTask::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.acquisition.AcquisitionTask)
  GOOGLE_DCHECK_NE(&from, this);
  const AcquisitionTask* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AcquisitionTask>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.acquisition.AcquisitionTask)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.acquisition.AcquisitionTask)
    MergeFrom(*source);
  }
}

void AcquisitionTask::MergeFrom(const AcquisitionTask& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.acquisition.AcquisitionTask)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  channels_.MergeFrom(from.channels_);
  if (from.max_buffer_size() != 0) {
    _internal_set_max_buffer_size(from._internal_max_buffer_size());
  }
  if (from.storage_unit_size() != 0) {
    _internal_set_storage_unit_size(from._internal_storage_unit_size());
  }
  if (from.time_switch_buffer_ms() != 0) {
    _internal_set_time_switch_buffer_ms(from._internal_time_switch_buffer_ms());
  }
  if (from.total_channel_num() != 0) {
    _internal_set_total_channel_num(from._internal_total_channel_num());
  }
  if (from.min_packet_size() != 0) {
    _internal_set_min_packet_size(from._internal_min_packet_size());
  }
}

void AcquisitionTask::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.acquisition.AcquisitionTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AcquisitionTask::CopyFrom(const AcquisitionTask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.acquisition.AcquisitionTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AcquisitionTask::IsInitialized() const {
  return true;
}

void AcquisitionTask::InternalSwap(AcquisitionTask* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  channels_.InternalSwap(&other->channels_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AcquisitionTask, min_packet_size_)
      + sizeof(AcquisitionTask::min_packet_size_)
      - PROTOBUF_FIELD_OFFSET(AcquisitionTask, max_buffer_size_)>(
          reinterpret_cast<char*>(&max_buffer_size_),
          reinterpret_cast<char*>(&other->max_buffer_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AcquisitionTask::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void NodeInfo::InitAsDefaultInstance() {
}
class NodeInfo::_Internal {
 public:
};

NodeInfo::NodeInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.acquisition.NodeInfo)
}
NodeInfo::NodeInfo(const NodeInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  node_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_node_id().empty()) {
    node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_node_id(),
      GetArena());
  }
  hostname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_hostname().empty()) {
    hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_hostname(),
      GetArena());
  }
  ip_address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ip_address().empty()) {
    ip_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_ip_address(),
      GetArena());
  }
  ::memcpy(&memory_size_, &from.memory_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&cpu_cores_) -
    reinterpret_cast<char*>(&memory_size_)) + sizeof(cpu_cores_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.acquisition.NodeInfo)
}

void NodeInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NodeInfo_acquisition_2eproto.base);
  node_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  hostname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ip_address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&memory_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cpu_cores_) -
      reinterpret_cast<char*>(&memory_size_)) + sizeof(cpu_cores_));
}

NodeInfo::~NodeInfo() {
  // @@protoc_insertion_point(destructor:openpni.distributed.acquisition.NodeInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NodeInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  node_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  hostname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ip_address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NodeInfo::ArenaDtor(void* object) {
  NodeInfo* _this = reinterpret_cast< NodeInfo* >(object);
  (void)_this;
}
void NodeInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NodeInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NodeInfo& NodeInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NodeInfo_acquisition_2eproto.base);
  return *internal_default_instance();
}


void NodeInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.acquisition.NodeInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  node_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  hostname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ip_address_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&memory_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cpu_cores_) -
      reinterpret_cast<char*>(&memory_size_)) + sizeof(cpu_cores_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NodeInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string node_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_node_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.acquisition.NodeInfo.node_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string hostname = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_hostname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.acquisition.NodeInfo.hostname"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string ip_address = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_ip_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.acquisition.NodeInfo.ip_address"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cpu_cores = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          cpu_cores_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 memory_size = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          memory_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NodeInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.acquisition.NodeInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string node_id = 1;
  if (this->node_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.acquisition.NodeInfo.node_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_node_id(), target);
  }

  // string hostname = 2;
  if (this->hostname().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hostname().data(), static_cast<int>(this->_internal_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.acquisition.NodeInfo.hostname");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_hostname(), target);
  }

  // string ip_address = 3;
  if (this->ip_address().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip_address().data(), static_cast<int>(this->_internal_ip_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.acquisition.NodeInfo.ip_address");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_ip_address(), target);
  }

  // uint32 cpu_cores = 4;
  if (this->cpu_cores() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_cpu_cores(), target);
  }

  // uint64 memory_size = 5;
  if (this->memory_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_memory_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.acquisition.NodeInfo)
  return target;
}

size_t NodeInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.acquisition.NodeInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string node_id = 1;
  if (this->node_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_node_id());
  }

  // string hostname = 2;
  if (this->hostname().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hostname());
  }

  // string ip_address = 3;
  if (this->ip_address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip_address());
  }

  // uint64 memory_size = 5;
  if (this->memory_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_memory_size());
  }

  // uint32 cpu_cores = 4;
  if (this->cpu_cores() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cpu_cores());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NodeInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.acquisition.NodeInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NodeInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.acquisition.NodeInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.acquisition.NodeInfo)
    MergeFrom(*source);
  }
}

void NodeInfo::MergeFrom(const NodeInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.acquisition.NodeInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.node_id().size() > 0) {
    _internal_set_node_id(from._internal_node_id());
  }
  if (from.hostname().size() > 0) {
    _internal_set_hostname(from._internal_hostname());
  }
  if (from.ip_address().size() > 0) {
    _internal_set_ip_address(from._internal_ip_address());
  }
  if (from.memory_size() != 0) {
    _internal_set_memory_size(from._internal_memory_size());
  }
  if (from.cpu_cores() != 0) {
    _internal_set_cpu_cores(from._internal_cpu_cores());
  }
}

void NodeInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.acquisition.NodeInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeInfo::CopyFrom(const NodeInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.acquisition.NodeInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeInfo::IsInitialized() const {
  return true;
}

void NodeInfo::InternalSwap(NodeInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  node_id_.Swap(&other->node_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  hostname_.Swap(&other->hostname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ip_address_.Swap(&other->ip_address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NodeInfo, cpu_cores_)
      + sizeof(NodeInfo::cpu_cores_)
      - PROTOBUF_FIELD_OFFSET(NodeInfo, memory_size_)>(
          reinterpret_cast<char*>(&memory_size_),
          reinterpret_cast<char*>(&other->memory_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NodeInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MasterCommand::InitAsDefaultInstance() {
  ::openpni::distributed::acquisition::_MasterCommand_default_instance_._instance.get_mutable()->task_ = const_cast< ::openpni::distributed::acquisition::AcquisitionTask*>(
      ::openpni::distributed::acquisition::AcquisitionTask::internal_default_instance());
}
class MasterCommand::_Internal {
 public:
  static const ::openpni::distributed::acquisition::AcquisitionTask& task(const MasterCommand* msg);
};

const ::openpni::distributed::acquisition::AcquisitionTask&
MasterCommand::_Internal::task(const MasterCommand* msg) {
  return *msg->task_;
}
MasterCommand::MasterCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.acquisition.MasterCommand)
}
MasterCommand::MasterCommand(const MasterCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_message().empty()) {
    message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_message(),
      GetArena());
  }
  if (from._internal_has_task()) {
    task_ = new ::openpni::distributed::acquisition::AcquisitionTask(*from.task_);
  } else {
    task_ = nullptr;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.acquisition.MasterCommand)
}

void MasterCommand::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MasterCommand_acquisition_2eproto.base);
  message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&task_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&task_)) + sizeof(type_));
}

MasterCommand::~MasterCommand() {
  // @@protoc_insertion_point(destructor:openpni.distributed.acquisition.MasterCommand)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MasterCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete task_;
}

void MasterCommand::ArenaDtor(void* object) {
  MasterCommand* _this = reinterpret_cast< MasterCommand* >(object);
  (void)_this;
}
void MasterCommand::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MasterCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MasterCommand& MasterCommand::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MasterCommand_acquisition_2eproto.base);
  return *internal_default_instance();
}


void MasterCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.acquisition.MasterCommand)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && task_ != nullptr) {
    delete task_;
  }
  task_ = nullptr;
  type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MasterCommand::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .openpni.distributed.acquisition.CommandType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::openpni::distributed::acquisition::CommandType>(val));
        } else goto handle_unusual;
        continue;
      // .openpni.distributed.acquisition.AcquisitionTask task = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_task(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.acquisition.MasterCommand.message"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MasterCommand::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.acquisition.MasterCommand)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .openpni.distributed.acquisition.CommandType type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // .openpni.distributed.acquisition.AcquisitionTask task = 2;
  if (this->has_task()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::task(this), target, stream);
  }

  // string message = 3;
  if (this->message().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.acquisition.MasterCommand.message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.acquisition.MasterCommand)
  return target;
}

size_t MasterCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.acquisition.MasterCommand)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 3;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .openpni.distributed.acquisition.AcquisitionTask task = 2;
  if (this->has_task()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *task_);
  }

  // .openpni.distributed.acquisition.CommandType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MasterCommand::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.acquisition.MasterCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const MasterCommand* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MasterCommand>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.acquisition.MasterCommand)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.acquisition.MasterCommand)
    MergeFrom(*source);
  }
}

void MasterCommand::MergeFrom(const MasterCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.acquisition.MasterCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {
    _internal_set_message(from._internal_message());
  }
  if (from.has_task()) {
    _internal_mutable_task()->::openpni::distributed::acquisition::AcquisitionTask::MergeFrom(from._internal_task());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void MasterCommand::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.acquisition.MasterCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MasterCommand::CopyFrom(const MasterCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.acquisition.MasterCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MasterCommand::IsInitialized() const {
  return true;
}

void MasterCommand::InternalSwap(MasterCommand* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  message_.Swap(&other->message_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MasterCommand, type_)
      + sizeof(MasterCommand::type_)
      - PROTOBUF_FIELD_OFFSET(MasterCommand, task_)>(
          reinterpret_cast<char*>(&task_),
          reinterpret_cast<char*>(&other->task_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MasterCommand::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void NodeStatus::InitAsDefaultInstance() {
  ::openpni::distributed::acquisition::_NodeStatus_default_instance_._instance.get_mutable()->info_ = const_cast< ::openpni::distributed::acquisition::NodeInfo*>(
      ::openpni::distributed::acquisition::NodeInfo::internal_default_instance());
}
class NodeStatus::_Internal {
 public:
  static const ::openpni::distributed::acquisition::NodeInfo& info(const NodeStatus* msg);
};

const ::openpni::distributed::acquisition::NodeInfo&
NodeStatus::_Internal::info(const NodeStatus* msg) {
  return *msg->info_;
}
NodeStatus::NodeStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.acquisition.NodeStatus)
}
NodeStatus::NodeStatus(const NodeStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  error_message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_error_message().empty()) {
    error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_error_message(),
      GetArena());
  }
  if (from._internal_has_info()) {
    info_ = new ::openpni::distributed::acquisition::NodeInfo(*from.info_);
  } else {
    info_ = nullptr;
  }
  ::memcpy(&current_speed_mpps_, &from.current_speed_mpps_,
    static_cast<size_t>(reinterpret_cast<char*>(&state_) -
    reinterpret_cast<char*>(&current_speed_mpps_)) + sizeof(state_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.acquisition.NodeStatus)
}

void NodeStatus::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NodeStatus_acquisition_2eproto.base);
  error_message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&info_)) + sizeof(state_));
}

NodeStatus::~NodeStatus() {
  // @@protoc_insertion_point(destructor:openpni.distributed.acquisition.NodeStatus)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NodeStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  error_message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete info_;
}

void NodeStatus::ArenaDtor(void* object) {
  NodeStatus* _this = reinterpret_cast< NodeStatus* >(object);
  (void)_this;
}
void NodeStatus::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NodeStatus::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NodeStatus& NodeStatus::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NodeStatus_acquisition_2eproto.base);
  return *internal_default_instance();
}


void NodeStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.acquisition.NodeStatus)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && info_ != nullptr) {
    delete info_;
  }
  info_ = nullptr;
  ::memset(&current_speed_mpps_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&current_speed_mpps_)) + sizeof(state_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NodeStatus::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .openpni.distributed.acquisition.NodeInfo info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .openpni.distributed.acquisition.NodeState state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::openpni::distributed::acquisition::NodeState>(val));
        } else goto handle_unusual;
        continue;
      // string error_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_error_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.acquisition.NodeStatus.error_message"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double current_speed_mpps = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          current_speed_mpps_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double current_bandwidth_mbps = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          current_bandwidth_mbps_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NodeStatus::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.acquisition.NodeStatus)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .openpni.distributed.acquisition.NodeInfo info = 1;
  if (this->has_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::info(this), target, stream);
  }

  // .openpni.distributed.acquisition.NodeState state = 2;
  if (this->state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_state(), target);
  }

  // string error_message = 3;
  if (this->error_message().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.acquisition.NodeStatus.error_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_error_message(), target);
  }

  // double current_speed_mpps = 4;
  if (!(this->current_speed_mpps() <= 0 && this->current_speed_mpps() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_current_speed_mpps(), target);
  }

  // double current_bandwidth_mbps = 5;
  if (!(this->current_bandwidth_mbps() <= 0 && this->current_bandwidth_mbps() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_current_bandwidth_mbps(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.acquisition.NodeStatus)
  return target;
}

size_t NodeStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.acquisition.NodeStatus)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 3;
  if (this->error_message().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // .openpni.distributed.acquisition.NodeInfo info = 1;
  if (this->has_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *info_);
  }

  // double current_speed_mpps = 4;
  if (!(this->current_speed_mpps() <= 0 && this->current_speed_mpps() >= 0)) {
    total_size += 1 + 8;
  }

  // double current_bandwidth_mbps = 5;
  if (!(this->current_bandwidth_mbps() <= 0 && this->current_bandwidth_mbps() >= 0)) {
    total_size += 1 + 8;
  }

  // .openpni.distributed.acquisition.NodeState state = 2;
  if (this->state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_state());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NodeStatus::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.acquisition.NodeStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeStatus* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NodeStatus>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.acquisition.NodeStatus)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.acquisition.NodeStatus)
    MergeFrom(*source);
  }
}

void NodeStatus::MergeFrom(const NodeStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.acquisition.NodeStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error_message().size() > 0) {
    _internal_set_error_message(from._internal_error_message());
  }
  if (from.has_info()) {
    _internal_mutable_info()->::openpni::distributed::acquisition::NodeInfo::MergeFrom(from._internal_info());
  }
  if (!(from.current_speed_mpps() <= 0 && from.current_speed_mpps() >= 0)) {
    _internal_set_current_speed_mpps(from._internal_current_speed_mpps());
  }
  if (!(from.current_bandwidth_mbps() <= 0 && from.current_bandwidth_mbps() >= 0)) {
    _internal_set_current_bandwidth_mbps(from._internal_current_bandwidth_mbps());
  }
  if (from.state() != 0) {
    _internal_set_state(from._internal_state());
  }
}

void NodeStatus::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.acquisition.NodeStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeStatus::CopyFrom(const NodeStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.acquisition.NodeStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeStatus::IsInitialized() const {
  return true;
}

void NodeStatus::InternalSwap(NodeStatus* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  error_message_.Swap(&other->error_message_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NodeStatus, state_)
      + sizeof(NodeStatus::state_)
      - PROTOBUF_FIELD_OFFSET(NodeStatus, info_)>(
          reinterpret_cast<char*>(&info_),
          reinterpret_cast<char*>(&other->info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NodeStatus::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace acquisition
}  // namespace distributed
}  // namespace openpni
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::openpni::distributed::acquisition::ChannelConfig* Arena::CreateMaybeMessage< ::openpni::distributed::acquisition::ChannelConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::acquisition::ChannelConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::acquisition::AcquisitionTask* Arena::CreateMaybeMessage< ::openpni::distributed::acquisition::AcquisitionTask >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::acquisition::AcquisitionTask >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::acquisition::NodeInfo* Arena::CreateMaybeMessage< ::openpni::distributed::acquisition::NodeInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::acquisition::NodeInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::acquisition::MasterCommand* Arena::CreateMaybeMessage< ::openpni::distributed::acquisition::MasterCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::acquisition::MasterCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::acquisition::NodeStatus* Arena::CreateMaybeMessage< ::openpni::distributed::acquisition::NodeStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::acquisition::NodeStatus >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
