// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: timesync.proto

#include "timesync.pb.h"
#include "timesync.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace openpni {
namespace distributed {
namespace timesync {

static const char* TimeSyncService_method_names[] = {
  "/openpni.distributed.timesync.TimeSyncService/SyncClock",
  "/openpni.distributed.timesync.TimeSyncService/GetSyncStats",
  "/openpni.distributed.timesync.TimeSyncService/StreamingSync",
};

std::unique_ptr< TimeSyncService::Stub> TimeSyncService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TimeSyncService::Stub> stub(new TimeSyncService::Stub(channel));
  return stub;
}

TimeSyncService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SyncClock_(TimeSyncService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSyncStats_(TimeSyncService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamingSync_(TimeSyncService_method_names[2], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status TimeSyncService::Stub::SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::openpni::distributed::timesync::ClockSyncResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SyncClock_, context, request, response);
}

void TimeSyncService::Stub::experimental_async::SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SyncClock_, context, request, response, std::move(f));
}

void TimeSyncService::Stub::experimental_async::SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SyncClock_, context, request, response, std::move(f));
}

void TimeSyncService::Stub::experimental_async::SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SyncClock_, context, request, response, reactor);
}

void TimeSyncService::Stub::experimental_async::SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SyncClock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>* TimeSyncService::Stub::AsyncSyncClockRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::openpni::distributed::timesync::ClockSyncResponse>::Create(channel_.get(), cq, rpcmethod_SyncClock_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>* TimeSyncService::Stub::PrepareAsyncSyncClockRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::openpni::distributed::timesync::ClockSyncResponse>::Create(channel_.get(), cq, rpcmethod_SyncClock_, context, request, false);
}

::grpc::Status TimeSyncService::Stub::GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::openpni::distributed::timesync::AllClientStats* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetSyncStats_, context, request, response);
}

void TimeSyncService::Stub::experimental_async::GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetSyncStats_, context, request, response, std::move(f));
}

void TimeSyncService::Stub::experimental_async::GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetSyncStats_, context, request, response, std::move(f));
}

void TimeSyncService::Stub::experimental_async::GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetSyncStats_, context, request, response, reactor);
}

void TimeSyncService::Stub::experimental_async::GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetSyncStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>* TimeSyncService::Stub::AsyncGetSyncStatsRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::openpni::distributed::timesync::AllClientStats>::Create(channel_.get(), cq, rpcmethod_GetSyncStats_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>* TimeSyncService::Stub::PrepareAsyncGetSyncStatsRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::openpni::distributed::timesync::AllClientStats>::Create(channel_.get(), cq, rpcmethod_GetSyncStats_, context, request, false);
}

::grpc::ClientReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* TimeSyncService::Stub::StreamingSyncRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>::Create(channel_.get(), rpcmethod_StreamingSync_, context);
}

void TimeSyncService::Stub::experimental_async::StreamingSync(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingSync_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* TimeSyncService::Stub::AsyncStreamingSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>::Create(channel_.get(), cq, rpcmethod_StreamingSync_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* TimeSyncService::Stub::PrepareAsyncStreamingSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>::Create(channel_.get(), cq, rpcmethod_StreamingSync_, context, false, nullptr);
}

TimeSyncService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TimeSyncService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TimeSyncService::Service, ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>(
          [](TimeSyncService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::openpni::distributed::timesync::ClockSyncRequest* req,
             ::openpni::distributed::timesync::ClockSyncResponse* resp) {
               return service->SyncClock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TimeSyncService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TimeSyncService::Service, ::openpni::distributed::timesync::EmptyRequest, ::openpni::distributed::timesync::AllClientStats>(
          [](TimeSyncService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::openpni::distributed::timesync::EmptyRequest* req,
             ::openpni::distributed::timesync::AllClientStats* resp) {
               return service->GetSyncStats(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TimeSyncService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< TimeSyncService::Service, ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>(
          [](TimeSyncService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::openpni::distributed::timesync::ClockSyncResponse,
             ::openpni::distributed::timesync::ClockSyncRequest>* stream) {
               return service->StreamingSync(ctx, stream);
             }, this)));
}

TimeSyncService::Service::~Service() {
}

::grpc::Status TimeSyncService::Service::SyncClock(::grpc::ServerContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TimeSyncService::Service::GetSyncStats(::grpc::ServerContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TimeSyncService::Service::StreamingSync(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace openpni
}  // namespace distributed
}  // namespace timesync

