// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timesync.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_timesync_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_timesync_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_timesync_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_timesync_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_timesync_2eproto;
namespace openpni {
namespace distributed {
namespace timesync {
class AllClientStats;
class AllClientStatsDefaultTypeInternal;
extern AllClientStatsDefaultTypeInternal _AllClientStats_default_instance_;
class ClientStats;
class ClientStatsDefaultTypeInternal;
extern ClientStatsDefaultTypeInternal _ClientStats_default_instance_;
class ClockSyncRequest;
class ClockSyncRequestDefaultTypeInternal;
extern ClockSyncRequestDefaultTypeInternal _ClockSyncRequest_default_instance_;
class ClockSyncResponse;
class ClockSyncResponseDefaultTypeInternal;
extern ClockSyncResponseDefaultTypeInternal _ClockSyncResponse_default_instance_;
class EmptyRequest;
class EmptyRequestDefaultTypeInternal;
extern EmptyRequestDefaultTypeInternal _EmptyRequest_default_instance_;
class TimeSyncStats;
class TimeSyncStatsDefaultTypeInternal;
extern TimeSyncStatsDefaultTypeInternal _TimeSyncStats_default_instance_;
}  // namespace timesync
}  // namespace distributed
}  // namespace openpni
PROTOBUF_NAMESPACE_OPEN
template<> ::openpni::distributed::timesync::AllClientStats* Arena::CreateMaybeMessage<::openpni::distributed::timesync::AllClientStats>(Arena*);
template<> ::openpni::distributed::timesync::ClientStats* Arena::CreateMaybeMessage<::openpni::distributed::timesync::ClientStats>(Arena*);
template<> ::openpni::distributed::timesync::ClockSyncRequest* Arena::CreateMaybeMessage<::openpni::distributed::timesync::ClockSyncRequest>(Arena*);
template<> ::openpni::distributed::timesync::ClockSyncResponse* Arena::CreateMaybeMessage<::openpni::distributed::timesync::ClockSyncResponse>(Arena*);
template<> ::openpni::distributed::timesync::EmptyRequest* Arena::CreateMaybeMessage<::openpni::distributed::timesync::EmptyRequest>(Arena*);
template<> ::openpni::distributed::timesync::TimeSyncStats* Arena::CreateMaybeMessage<::openpni::distributed::timesync::TimeSyncStats>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace openpni {
namespace distributed {
namespace timesync {

// ===================================================================

class ClockSyncRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.timesync.ClockSyncRequest) */ {
 public:
  inline ClockSyncRequest() : ClockSyncRequest(nullptr) {};
  virtual ~ClockSyncRequest();

  ClockSyncRequest(const ClockSyncRequest& from);
  ClockSyncRequest(ClockSyncRequest&& from) noexcept
    : ClockSyncRequest() {
    *this = ::std::move(from);
  }

  inline ClockSyncRequest& operator=(const ClockSyncRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClockSyncRequest& operator=(ClockSyncRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ClockSyncRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClockSyncRequest* internal_default_instance() {
    return reinterpret_cast<const ClockSyncRequest*>(
               &_ClockSyncRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClockSyncRequest& a, ClockSyncRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ClockSyncRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClockSyncRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClockSyncRequest* New() const final {
    return CreateMaybeMessage<ClockSyncRequest>(nullptr);
  }

  ClockSyncRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClockSyncRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClockSyncRequest& from);
  void MergeFrom(const ClockSyncRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClockSyncRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.timesync.ClockSyncRequest";
  }
  protected:
  explicit ClockSyncRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_timesync_2eproto);
    return ::descriptor_table_timesync_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientHostnameFieldNumber = 3,
    kClientLocalTimeNsFieldNumber = 1,
    kClientIdFieldNumber = 2,
  };
  // string client_hostname = 3;
  void clear_client_hostname();
  const std::string& client_hostname() const;
  void set_client_hostname(const std::string& value);
  void set_client_hostname(std::string&& value);
  void set_client_hostname(const char* value);
  void set_client_hostname(const char* value, size_t size);
  std::string* mutable_client_hostname();
  std::string* release_client_hostname();
  void set_allocated_client_hostname(std::string* client_hostname);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_client_hostname();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_client_hostname(
      std::string* client_hostname);
  private:
  const std::string& _internal_client_hostname() const;
  void _internal_set_client_hostname(const std::string& value);
  std::string* _internal_mutable_client_hostname();
  public:

  // uint64 client_local_time_ns = 1;
  void clear_client_local_time_ns();
  ::PROTOBUF_NAMESPACE_ID::uint64 client_local_time_ns() const;
  void set_client_local_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_client_local_time_ns() const;
  void _internal_set_client_local_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 client_id = 2;
  void clear_client_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 client_id() const;
  void set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_client_id() const;
  void _internal_set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.timesync.ClockSyncRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_hostname_;
  ::PROTOBUF_NAMESPACE_ID::uint64 client_local_time_ns_;
  ::PROTOBUF_NAMESPACE_ID::uint32 client_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_timesync_2eproto;
};
// -------------------------------------------------------------------

class ClockSyncResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.timesync.ClockSyncResponse) */ {
 public:
  inline ClockSyncResponse() : ClockSyncResponse(nullptr) {};
  virtual ~ClockSyncResponse();

  ClockSyncResponse(const ClockSyncResponse& from);
  ClockSyncResponse(ClockSyncResponse&& from) noexcept
    : ClockSyncResponse() {
    *this = ::std::move(from);
  }

  inline ClockSyncResponse& operator=(const ClockSyncResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClockSyncResponse& operator=(ClockSyncResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ClockSyncResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClockSyncResponse* internal_default_instance() {
    return reinterpret_cast<const ClockSyncResponse*>(
               &_ClockSyncResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ClockSyncResponse& a, ClockSyncResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ClockSyncResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClockSyncResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClockSyncResponse* New() const final {
    return CreateMaybeMessage<ClockSyncResponse>(nullptr);
  }

  ClockSyncResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClockSyncResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClockSyncResponse& from);
  void MergeFrom(const ClockSyncResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClockSyncResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.timesync.ClockSyncResponse";
  }
  protected:
  explicit ClockSyncResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_timesync_2eproto);
    return ::descriptor_table_timesync_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTimeNsFieldNumber = 1,
    kClientRequestTimeNsFieldNumber = 2,
    kResponseTimeNsFieldNumber = 3,
    kEstimatedClockOffsetNsFieldNumber = 4,
    kNetworkDelayEstimateMsFieldNumber = 5,
  };
  // uint64 server_time_ns = 1;
  void clear_server_time_ns();
  ::PROTOBUF_NAMESPACE_ID::uint64 server_time_ns() const;
  void set_server_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_server_time_ns() const;
  void _internal_set_server_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 client_request_time_ns = 2;
  void clear_client_request_time_ns();
  ::PROTOBUF_NAMESPACE_ID::uint64 client_request_time_ns() const;
  void set_client_request_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_client_request_time_ns() const;
  void _internal_set_client_request_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 response_time_ns = 3;
  void clear_response_time_ns();
  ::PROTOBUF_NAMESPACE_ID::uint64 response_time_ns() const;
  void set_response_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_response_time_ns() const;
  void _internal_set_response_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int64 estimated_clock_offset_ns = 4;
  void clear_estimated_clock_offset_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 estimated_clock_offset_ns() const;
  void set_estimated_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_estimated_clock_offset_ns() const;
  void _internal_set_estimated_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // float network_delay_estimate_ms = 5;
  void clear_network_delay_estimate_ms();
  float network_delay_estimate_ms() const;
  void set_network_delay_estimate_ms(float value);
  private:
  float _internal_network_delay_estimate_ms() const;
  void _internal_set_network_delay_estimate_ms(float value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.timesync.ClockSyncResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 server_time_ns_;
  ::PROTOBUF_NAMESPACE_ID::uint64 client_request_time_ns_;
  ::PROTOBUF_NAMESPACE_ID::uint64 response_time_ns_;
  ::PROTOBUF_NAMESPACE_ID::int64 estimated_clock_offset_ns_;
  float network_delay_estimate_ms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_timesync_2eproto;
};
// -------------------------------------------------------------------

class TimeSyncStats PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.timesync.TimeSyncStats) */ {
 public:
  inline TimeSyncStats() : TimeSyncStats(nullptr) {};
  virtual ~TimeSyncStats();

  TimeSyncStats(const TimeSyncStats& from);
  TimeSyncStats(TimeSyncStats&& from) noexcept
    : TimeSyncStats() {
    *this = ::std::move(from);
  }

  inline TimeSyncStats& operator=(const TimeSyncStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimeSyncStats& operator=(TimeSyncStats&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TimeSyncStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TimeSyncStats* internal_default_instance() {
    return reinterpret_cast<const TimeSyncStats*>(
               &_TimeSyncStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TimeSyncStats& a, TimeSyncStats& b) {
    a.Swap(&b);
  }
  inline void Swap(TimeSyncStats* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TimeSyncStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TimeSyncStats* New() const final {
    return CreateMaybeMessage<TimeSyncStats>(nullptr);
  }

  TimeSyncStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TimeSyncStats>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TimeSyncStats& from);
  void MergeFrom(const TimeSyncStats& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimeSyncStats* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.timesync.TimeSyncStats";
  }
  protected:
  explicit TimeSyncStats(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_timesync_2eproto);
    return ::descriptor_table_timesync_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLastSyncTimeFieldNumber = 2,
    kClientIdFieldNumber = 1,
    kClockDriftRateFieldNumber = 4,
    kClockOffsetNsFieldNumber = 3,
    kSyncCountFieldNumber = 5,
  };
  // uint64 last_sync_time = 2;
  void clear_last_sync_time();
  ::PROTOBUF_NAMESPACE_ID::uint64 last_sync_time() const;
  void set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_last_sync_time() const;
  void _internal_set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 client_id = 1;
  void clear_client_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 client_id() const;
  void set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_client_id() const;
  void _internal_set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float clock_drift_rate = 4;
  void clear_clock_drift_rate();
  float clock_drift_rate() const;
  void set_clock_drift_rate(float value);
  private:
  float _internal_clock_drift_rate() const;
  void _internal_set_clock_drift_rate(float value);
  public:

  // int64 clock_offset_ns = 3;
  void clear_clock_offset_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 clock_offset_ns() const;
  void set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_clock_offset_ns() const;
  void _internal_set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // uint32 sync_count = 5;
  void clear_sync_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 sync_count() const;
  void set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_sync_count() const;
  void _internal_set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.timesync.TimeSyncStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 last_sync_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 client_id_;
  float clock_drift_rate_;
  ::PROTOBUF_NAMESPACE_ID::int64 clock_offset_ns_;
  ::PROTOBUF_NAMESPACE_ID::uint32 sync_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_timesync_2eproto;
};
// -------------------------------------------------------------------

class AllClientStats PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.timesync.AllClientStats) */ {
 public:
  inline AllClientStats() : AllClientStats(nullptr) {};
  virtual ~AllClientStats();

  AllClientStats(const AllClientStats& from);
  AllClientStats(AllClientStats&& from) noexcept
    : AllClientStats() {
    *this = ::std::move(from);
  }

  inline AllClientStats& operator=(const AllClientStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllClientStats& operator=(AllClientStats&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AllClientStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AllClientStats* internal_default_instance() {
    return reinterpret_cast<const AllClientStats*>(
               &_AllClientStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AllClientStats& a, AllClientStats& b) {
    a.Swap(&b);
  }
  inline void Swap(AllClientStats* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllClientStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AllClientStats* New() const final {
    return CreateMaybeMessage<AllClientStats>(nullptr);
  }

  AllClientStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AllClientStats>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AllClientStats& from);
  void MergeFrom(const AllClientStats& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllClientStats* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.timesync.AllClientStats";
  }
  protected:
  explicit AllClientStats(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_timesync_2eproto);
    return ::descriptor_table_timesync_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientsFieldNumber = 1,
  };
  // repeated .openpni.distributed.timesync.ClientStats clients = 1;
  int clients_size() const;
  private:
  int _internal_clients_size() const;
  public:
  void clear_clients();
  ::openpni::distributed::timesync::ClientStats* mutable_clients(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::timesync::ClientStats >*
      mutable_clients();
  private:
  const ::openpni::distributed::timesync::ClientStats& _internal_clients(int index) const;
  ::openpni::distributed::timesync::ClientStats* _internal_add_clients();
  public:
  const ::openpni::distributed::timesync::ClientStats& clients(int index) const;
  ::openpni::distributed::timesync::ClientStats* add_clients();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::timesync::ClientStats >&
      clients() const;

  // @@protoc_insertion_point(class_scope:openpni.distributed.timesync.AllClientStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::timesync::ClientStats > clients_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_timesync_2eproto;
};
// -------------------------------------------------------------------

class ClientStats PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.timesync.ClientStats) */ {
 public:
  inline ClientStats() : ClientStats(nullptr) {};
  virtual ~ClientStats();

  ClientStats(const ClientStats& from);
  ClientStats(ClientStats&& from) noexcept
    : ClientStats() {
    *this = ::std::move(from);
  }

  inline ClientStats& operator=(const ClientStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientStats& operator=(ClientStats&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ClientStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientStats* internal_default_instance() {
    return reinterpret_cast<const ClientStats*>(
               &_ClientStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ClientStats& a, ClientStats& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientStats* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientStats* New() const final {
    return CreateMaybeMessage<ClientStats>(nullptr);
  }

  ClientStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientStats>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientStats& from);
  void MergeFrom(const ClientStats& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientStats* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.timesync.ClientStats";
  }
  protected:
  explicit ClientStats(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_timesync_2eproto);
    return ::descriptor_table_timesync_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostnameFieldNumber = 2,
    kLastSyncTimeFieldNumber = 3,
    kClientIdFieldNumber = 1,
    kClockDriftRateFieldNumber = 5,
    kClockOffsetNsFieldNumber = 4,
    kSyncCountFieldNumber = 6,
  };
  // string hostname = 2;
  void clear_hostname();
  const std::string& hostname() const;
  void set_hostname(const std::string& value);
  void set_hostname(std::string&& value);
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  std::string* mutable_hostname();
  std::string* release_hostname();
  void set_allocated_hostname(std::string* hostname);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_hostname();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_hostname(
      std::string* hostname);
  private:
  const std::string& _internal_hostname() const;
  void _internal_set_hostname(const std::string& value);
  std::string* _internal_mutable_hostname();
  public:

  // uint64 last_sync_time = 3;
  void clear_last_sync_time();
  ::PROTOBUF_NAMESPACE_ID::uint64 last_sync_time() const;
  void set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_last_sync_time() const;
  void _internal_set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 client_id = 1;
  void clear_client_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 client_id() const;
  void set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_client_id() const;
  void _internal_set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float clock_drift_rate = 5;
  void clear_clock_drift_rate();
  float clock_drift_rate() const;
  void set_clock_drift_rate(float value);
  private:
  float _internal_clock_drift_rate() const;
  void _internal_set_clock_drift_rate(float value);
  public:

  // int64 clock_offset_ns = 4;
  void clear_clock_offset_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 clock_offset_ns() const;
  void set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_clock_offset_ns() const;
  void _internal_set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // uint32 sync_count = 6;
  void clear_sync_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 sync_count() const;
  void set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_sync_count() const;
  void _internal_set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:openpni.distributed.timesync.ClientStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hostname_;
  ::PROTOBUF_NAMESPACE_ID::uint64 last_sync_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 client_id_;
  float clock_drift_rate_;
  ::PROTOBUF_NAMESPACE_ID::int64 clock_offset_ns_;
  ::PROTOBUF_NAMESPACE_ID::uint32 sync_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_timesync_2eproto;
};
// -------------------------------------------------------------------

class EmptyRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openpni.distributed.timesync.EmptyRequest) */ {
 public:
  inline EmptyRequest() : EmptyRequest(nullptr) {};
  virtual ~EmptyRequest();

  EmptyRequest(const EmptyRequest& from);
  EmptyRequest(EmptyRequest&& from) noexcept
    : EmptyRequest() {
    *this = ::std::move(from);
  }

  inline EmptyRequest& operator=(const EmptyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EmptyRequest& operator=(EmptyRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EmptyRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EmptyRequest* internal_default_instance() {
    return reinterpret_cast<const EmptyRequest*>(
               &_EmptyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(EmptyRequest& a, EmptyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EmptyRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EmptyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EmptyRequest* New() const final {
    return CreateMaybeMessage<EmptyRequest>(nullptr);
  }

  EmptyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EmptyRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EmptyRequest& from);
  void MergeFrom(const EmptyRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EmptyRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openpni.distributed.timesync.EmptyRequest";
  }
  protected:
  explicit EmptyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_timesync_2eproto);
    return ::descriptor_table_timesync_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:openpni.distributed.timesync.EmptyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_timesync_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClockSyncRequest

// uint64 client_local_time_ns = 1;
inline void ClockSyncRequest::clear_client_local_time_ns() {
  client_local_time_ns_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncRequest::_internal_client_local_time_ns() const {
  return client_local_time_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncRequest::client_local_time_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncRequest.client_local_time_ns)
  return _internal_client_local_time_ns();
}
inline void ClockSyncRequest::_internal_set_client_local_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  client_local_time_ns_ = value;
}
inline void ClockSyncRequest::set_client_local_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_client_local_time_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncRequest.client_local_time_ns)
}

// uint32 client_id = 2;
inline void ClockSyncRequest::clear_client_id() {
  client_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClockSyncRequest::_internal_client_id() const {
  return client_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClockSyncRequest::client_id() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncRequest.client_id)
  return _internal_client_id();
}
inline void ClockSyncRequest::_internal_set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  client_id_ = value;
}
inline void ClockSyncRequest::set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_client_id(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncRequest.client_id)
}

// string client_hostname = 3;
inline void ClockSyncRequest::clear_client_hostname() {
  client_hostname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ClockSyncRequest::client_hostname() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
  return _internal_client_hostname();
}
inline void ClockSyncRequest::set_client_hostname(const std::string& value) {
  _internal_set_client_hostname(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
}
inline std::string* ClockSyncRequest::mutable_client_hostname() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
  return _internal_mutable_client_hostname();
}
inline const std::string& ClockSyncRequest::_internal_client_hostname() const {
  return client_hostname_.Get();
}
inline void ClockSyncRequest::_internal_set_client_hostname(const std::string& value) {
  
  client_hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ClockSyncRequest::set_client_hostname(std::string&& value) {
  
  client_hostname_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
}
inline void ClockSyncRequest::set_client_hostname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  client_hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
}
inline void ClockSyncRequest::set_client_hostname(const char* value,
    size_t size) {
  
  client_hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
}
inline std::string* ClockSyncRequest::_internal_mutable_client_hostname() {
  
  return client_hostname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ClockSyncRequest::release_client_hostname() {
  // @@protoc_insertion_point(field_release:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
  return client_hostname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ClockSyncRequest::set_allocated_client_hostname(std::string* client_hostname) {
  if (client_hostname != nullptr) {
    
  } else {
    
  }
  client_hostname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), client_hostname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
}
inline std::string* ClockSyncRequest::unsafe_arena_release_client_hostname() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return client_hostname_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ClockSyncRequest::unsafe_arena_set_allocated_client_hostname(
    std::string* client_hostname) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (client_hostname != nullptr) {
    
  } else {
    
  }
  client_hostname_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      client_hostname, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.timesync.ClockSyncRequest.client_hostname)
}

// -------------------------------------------------------------------

// ClockSyncResponse

// uint64 server_time_ns = 1;
inline void ClockSyncResponse::clear_server_time_ns() {
  server_time_ns_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncResponse::_internal_server_time_ns() const {
  return server_time_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncResponse::server_time_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncResponse.server_time_ns)
  return _internal_server_time_ns();
}
inline void ClockSyncResponse::_internal_set_server_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  server_time_ns_ = value;
}
inline void ClockSyncResponse::set_server_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_server_time_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncResponse.server_time_ns)
}

// uint64 client_request_time_ns = 2;
inline void ClockSyncResponse::clear_client_request_time_ns() {
  client_request_time_ns_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncResponse::_internal_client_request_time_ns() const {
  return client_request_time_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncResponse::client_request_time_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncResponse.client_request_time_ns)
  return _internal_client_request_time_ns();
}
inline void ClockSyncResponse::_internal_set_client_request_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  client_request_time_ns_ = value;
}
inline void ClockSyncResponse::set_client_request_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_client_request_time_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncResponse.client_request_time_ns)
}

// uint64 response_time_ns = 3;
inline void ClockSyncResponse::clear_response_time_ns() {
  response_time_ns_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncResponse::_internal_response_time_ns() const {
  return response_time_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClockSyncResponse::response_time_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncResponse.response_time_ns)
  return _internal_response_time_ns();
}
inline void ClockSyncResponse::_internal_set_response_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  response_time_ns_ = value;
}
inline void ClockSyncResponse::set_response_time_ns(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_response_time_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncResponse.response_time_ns)
}

// int64 estimated_clock_offset_ns = 4;
inline void ClockSyncResponse::clear_estimated_clock_offset_ns() {
  estimated_clock_offset_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ClockSyncResponse::_internal_estimated_clock_offset_ns() const {
  return estimated_clock_offset_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ClockSyncResponse::estimated_clock_offset_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncResponse.estimated_clock_offset_ns)
  return _internal_estimated_clock_offset_ns();
}
inline void ClockSyncResponse::_internal_set_estimated_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  estimated_clock_offset_ns_ = value;
}
inline void ClockSyncResponse::set_estimated_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_estimated_clock_offset_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncResponse.estimated_clock_offset_ns)
}

// float network_delay_estimate_ms = 5;
inline void ClockSyncResponse::clear_network_delay_estimate_ms() {
  network_delay_estimate_ms_ = 0;
}
inline float ClockSyncResponse::_internal_network_delay_estimate_ms() const {
  return network_delay_estimate_ms_;
}
inline float ClockSyncResponse::network_delay_estimate_ms() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClockSyncResponse.network_delay_estimate_ms)
  return _internal_network_delay_estimate_ms();
}
inline void ClockSyncResponse::_internal_set_network_delay_estimate_ms(float value) {
  
  network_delay_estimate_ms_ = value;
}
inline void ClockSyncResponse::set_network_delay_estimate_ms(float value) {
  _internal_set_network_delay_estimate_ms(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClockSyncResponse.network_delay_estimate_ms)
}

// -------------------------------------------------------------------

// TimeSyncStats

// uint32 client_id = 1;
inline void TimeSyncStats::clear_client_id() {
  client_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TimeSyncStats::_internal_client_id() const {
  return client_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TimeSyncStats::client_id() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.TimeSyncStats.client_id)
  return _internal_client_id();
}
inline void TimeSyncStats::_internal_set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  client_id_ = value;
}
inline void TimeSyncStats::set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_client_id(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.TimeSyncStats.client_id)
}

// uint64 last_sync_time = 2;
inline void TimeSyncStats::clear_last_sync_time() {
  last_sync_time_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TimeSyncStats::_internal_last_sync_time() const {
  return last_sync_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TimeSyncStats::last_sync_time() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.TimeSyncStats.last_sync_time)
  return _internal_last_sync_time();
}
inline void TimeSyncStats::_internal_set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  last_sync_time_ = value;
}
inline void TimeSyncStats::set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_last_sync_time(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.TimeSyncStats.last_sync_time)
}

// int64 clock_offset_ns = 3;
inline void TimeSyncStats::clear_clock_offset_ns() {
  clock_offset_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TimeSyncStats::_internal_clock_offset_ns() const {
  return clock_offset_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TimeSyncStats::clock_offset_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.TimeSyncStats.clock_offset_ns)
  return _internal_clock_offset_ns();
}
inline void TimeSyncStats::_internal_set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  clock_offset_ns_ = value;
}
inline void TimeSyncStats::set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_clock_offset_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.TimeSyncStats.clock_offset_ns)
}

// float clock_drift_rate = 4;
inline void TimeSyncStats::clear_clock_drift_rate() {
  clock_drift_rate_ = 0;
}
inline float TimeSyncStats::_internal_clock_drift_rate() const {
  return clock_drift_rate_;
}
inline float TimeSyncStats::clock_drift_rate() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.TimeSyncStats.clock_drift_rate)
  return _internal_clock_drift_rate();
}
inline void TimeSyncStats::_internal_set_clock_drift_rate(float value) {
  
  clock_drift_rate_ = value;
}
inline void TimeSyncStats::set_clock_drift_rate(float value) {
  _internal_set_clock_drift_rate(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.TimeSyncStats.clock_drift_rate)
}

// uint32 sync_count = 5;
inline void TimeSyncStats::clear_sync_count() {
  sync_count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TimeSyncStats::_internal_sync_count() const {
  return sync_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TimeSyncStats::sync_count() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.TimeSyncStats.sync_count)
  return _internal_sync_count();
}
inline void TimeSyncStats::_internal_set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  sync_count_ = value;
}
inline void TimeSyncStats::set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_sync_count(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.TimeSyncStats.sync_count)
}

// -------------------------------------------------------------------

// AllClientStats

// repeated .openpni.distributed.timesync.ClientStats clients = 1;
inline int AllClientStats::_internal_clients_size() const {
  return clients_.size();
}
inline int AllClientStats::clients_size() const {
  return _internal_clients_size();
}
inline void AllClientStats::clear_clients() {
  clients_.Clear();
}
inline ::openpni::distributed::timesync::ClientStats* AllClientStats::mutable_clients(int index) {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.timesync.AllClientStats.clients)
  return clients_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::timesync::ClientStats >*
AllClientStats::mutable_clients() {
  // @@protoc_insertion_point(field_mutable_list:openpni.distributed.timesync.AllClientStats.clients)
  return &clients_;
}
inline const ::openpni::distributed::timesync::ClientStats& AllClientStats::_internal_clients(int index) const {
  return clients_.Get(index);
}
inline const ::openpni::distributed::timesync::ClientStats& AllClientStats::clients(int index) const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.AllClientStats.clients)
  return _internal_clients(index);
}
inline ::openpni::distributed::timesync::ClientStats* AllClientStats::_internal_add_clients() {
  return clients_.Add();
}
inline ::openpni::distributed::timesync::ClientStats* AllClientStats::add_clients() {
  // @@protoc_insertion_point(field_add:openpni.distributed.timesync.AllClientStats.clients)
  return _internal_add_clients();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::openpni::distributed::timesync::ClientStats >&
AllClientStats::clients() const {
  // @@protoc_insertion_point(field_list:openpni.distributed.timesync.AllClientStats.clients)
  return clients_;
}

// -------------------------------------------------------------------

// ClientStats

// uint32 client_id = 1;
inline void ClientStats::clear_client_id() {
  client_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientStats::_internal_client_id() const {
  return client_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientStats::client_id() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClientStats.client_id)
  return _internal_client_id();
}
inline void ClientStats::_internal_set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  client_id_ = value;
}
inline void ClientStats::set_client_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_client_id(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClientStats.client_id)
}

// string hostname = 2;
inline void ClientStats::clear_hostname() {
  hostname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ClientStats::hostname() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClientStats.hostname)
  return _internal_hostname();
}
inline void ClientStats::set_hostname(const std::string& value) {
  _internal_set_hostname(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClientStats.hostname)
}
inline std::string* ClientStats::mutable_hostname() {
  // @@protoc_insertion_point(field_mutable:openpni.distributed.timesync.ClientStats.hostname)
  return _internal_mutable_hostname();
}
inline const std::string& ClientStats::_internal_hostname() const {
  return hostname_.Get();
}
inline void ClientStats::_internal_set_hostname(const std::string& value) {
  
  hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ClientStats::set_hostname(std::string&& value) {
  
  hostname_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openpni.distributed.timesync.ClientStats.hostname)
}
inline void ClientStats::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openpni.distributed.timesync.ClientStats.hostname)
}
inline void ClientStats::set_hostname(const char* value,
    size_t size) {
  
  hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openpni.distributed.timesync.ClientStats.hostname)
}
inline std::string* ClientStats::_internal_mutable_hostname() {
  
  return hostname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ClientStats::release_hostname() {
  // @@protoc_insertion_point(field_release:openpni.distributed.timesync.ClientStats.hostname)
  return hostname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ClientStats::set_allocated_hostname(std::string* hostname) {
  if (hostname != nullptr) {
    
  } else {
    
  }
  hostname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), hostname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openpni.distributed.timesync.ClientStats.hostname)
}
inline std::string* ClientStats::unsafe_arena_release_hostname() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openpni.distributed.timesync.ClientStats.hostname)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return hostname_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ClientStats::unsafe_arena_set_allocated_hostname(
    std::string* hostname) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (hostname != nullptr) {
    
  } else {
    
  }
  hostname_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      hostname, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openpni.distributed.timesync.ClientStats.hostname)
}

// uint64 last_sync_time = 3;
inline void ClientStats::clear_last_sync_time() {
  last_sync_time_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientStats::_internal_last_sync_time() const {
  return last_sync_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientStats::last_sync_time() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClientStats.last_sync_time)
  return _internal_last_sync_time();
}
inline void ClientStats::_internal_set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  last_sync_time_ = value;
}
inline void ClientStats::set_last_sync_time(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_last_sync_time(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClientStats.last_sync_time)
}

// int64 clock_offset_ns = 4;
inline void ClientStats::clear_clock_offset_ns() {
  clock_offset_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ClientStats::_internal_clock_offset_ns() const {
  return clock_offset_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ClientStats::clock_offset_ns() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClientStats.clock_offset_ns)
  return _internal_clock_offset_ns();
}
inline void ClientStats::_internal_set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  clock_offset_ns_ = value;
}
inline void ClientStats::set_clock_offset_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_clock_offset_ns(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClientStats.clock_offset_ns)
}

// float clock_drift_rate = 5;
inline void ClientStats::clear_clock_drift_rate() {
  clock_drift_rate_ = 0;
}
inline float ClientStats::_internal_clock_drift_rate() const {
  return clock_drift_rate_;
}
inline float ClientStats::clock_drift_rate() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClientStats.clock_drift_rate)
  return _internal_clock_drift_rate();
}
inline void ClientStats::_internal_set_clock_drift_rate(float value) {
  
  clock_drift_rate_ = value;
}
inline void ClientStats::set_clock_drift_rate(float value) {
  _internal_set_clock_drift_rate(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClientStats.clock_drift_rate)
}

// uint32 sync_count = 6;
inline void ClientStats::clear_sync_count() {
  sync_count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientStats::_internal_sync_count() const {
  return sync_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientStats::sync_count() const {
  // @@protoc_insertion_point(field_get:openpni.distributed.timesync.ClientStats.sync_count)
  return _internal_sync_count();
}
inline void ClientStats::_internal_set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  sync_count_ = value;
}
inline void ClientStats::set_sync_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_sync_count(value);
  // @@protoc_insertion_point(field_set:openpni.distributed.timesync.ClientStats.sync_count)
}

// -------------------------------------------------------------------

// EmptyRequest

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace timesync
}  // namespace distributed
}  // namespace openpni

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_timesync_2eproto
