// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: timesync.proto
#ifndef GRPC_timesync_2eproto__INCLUDED
#define GRPC_timesync_2eproto__INCLUDED

#include "timesync.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace openpni {
namespace distributed {
namespace timesync {

class TimeSyncService final {
 public:
  static constexpr char const* service_full_name() {
    return "openpni.distributed.timesync.TimeSyncService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 客户端向服务器进行时钟同步
    virtual ::grpc::Status SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::openpni::distributed::timesync::ClockSyncResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::ClockSyncResponse>> AsyncSyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::ClockSyncResponse>>(AsyncSyncClockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::ClockSyncResponse>> PrepareAsyncSyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::ClockSyncResponse>>(PrepareAsyncSyncClockRaw(context, request, cq));
    }
    // 查询同步统计信息
    virtual ::grpc::Status GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::openpni::distributed::timesync::AllClientStats* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::AllClientStats>> AsyncGetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::AllClientStats>>(AsyncGetSyncStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::AllClientStats>> PrepareAsyncGetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::AllClientStats>>(PrepareAsyncGetSyncStatsRaw(context, request, cq));
    }
    // 流式同步（持续保持时钟同步）
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>> StreamingSync(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>>(StreamingSyncRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>> AsyncStreamingSync(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>>(AsyncStreamingSyncRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>> PrepareAsyncStreamingSync(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>>(PrepareAsyncStreamingSyncRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // 客户端向服务器进行时钟同步
      virtual void SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // 查询同步统计信息
      virtual void GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // 流式同步（持续保持时钟同步）
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StreamingSync(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>* reactor) = 0;
      #else
      virtual void StreamingSync(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::ClockSyncResponse>* AsyncSyncClockRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::ClockSyncResponse>* PrepareAsyncSyncClockRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::AllClientStats>* AsyncGetSyncStatsRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openpni::distributed::timesync::AllClientStats>* PrepareAsyncGetSyncStatsRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* StreamingSyncRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* AsyncStreamingSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* PrepareAsyncStreamingSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::openpni::distributed::timesync::ClockSyncResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>> AsyncSyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>>(AsyncSyncClockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>> PrepareAsyncSyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>>(PrepareAsyncSyncClockRaw(context, request, cq));
    }
    ::grpc::Status GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::openpni::distributed::timesync::AllClientStats* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>> AsyncGetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>>(AsyncGetSyncStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>> PrepareAsyncGetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>>(PrepareAsyncGetSyncStatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>> StreamingSync(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>>(StreamingSyncRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>> AsyncStreamingSync(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>>(AsyncStreamingSyncRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>> PrepareAsyncStreamingSync(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>>(PrepareAsyncStreamingSyncRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, std::function<void(::grpc::Status)>) override;
      void SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SyncClock(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SyncClock(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::ClockSyncResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, std::function<void(::grpc::Status)>) override;
      void GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetSyncStats(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetSyncStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openpni::distributed::timesync::AllClientStats* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StreamingSync(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>* reactor) override;
      #else
      void StreamingSync(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>* AsyncSyncClockRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::ClockSyncResponse>* PrepareAsyncSyncClockRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::ClockSyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>* AsyncGetSyncStatsRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openpni::distributed::timesync::AllClientStats>* PrepareAsyncGetSyncStatsRaw(::grpc::ClientContext* context, const ::openpni::distributed::timesync::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* StreamingSyncRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* AsyncStreamingSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* PrepareAsyncStreamingSyncRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SyncClock_;
    const ::grpc::internal::RpcMethod rpcmethod_GetSyncStats_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamingSync_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 客户端向服务器进行时钟同步
    virtual ::grpc::Status SyncClock(::grpc::ServerContext* context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response);
    // 查询同步统计信息
    virtual ::grpc::Status GetSyncStats(::grpc::ServerContext* context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response);
    // 流式同步（持续保持时钟同步）
    virtual ::grpc::Status StreamingSync(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_SyncClock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SyncClock() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SyncClock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncClock(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncClock(::grpc::ServerContext* context, ::openpni::distributed::timesync::ClockSyncRequest* request, ::grpc::ServerAsyncResponseWriter< ::openpni::distributed::timesync::ClockSyncResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSyncStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSyncStats() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetSyncStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSyncStats(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSyncStats(::grpc::ServerContext* context, ::openpni::distributed::timesync::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::openpni::distributed::timesync::AllClientStats>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamingSync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamingSync() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamingSync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingSync(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingSync(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SyncClock<WithAsyncMethod_GetSyncStats<WithAsyncMethod_StreamingSync<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SyncClock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SyncClock() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openpni::distributed::timesync::ClockSyncRequest* request, ::openpni::distributed::timesync::ClockSyncResponse* response) { return this->SyncClock(context, request, response); }));}
    void SetMessageAllocatorFor_SyncClock(
        ::grpc::experimental::MessageAllocator< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SyncClock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncClock(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SyncClock(
      ::grpc::CallbackServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SyncClock(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetSyncStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetSyncStats() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::openpni::distributed::timesync::EmptyRequest, ::openpni::distributed::timesync::AllClientStats>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openpni::distributed::timesync::EmptyRequest* request, ::openpni::distributed::timesync::AllClientStats* response) { return this->GetSyncStats(context, request, response); }));}
    void SetMessageAllocatorFor_GetSyncStats(
        ::grpc::experimental::MessageAllocator< ::openpni::distributed::timesync::EmptyRequest, ::openpni::distributed::timesync::AllClientStats>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::openpni::distributed::timesync::EmptyRequest, ::openpni::distributed::timesync::AllClientStats>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetSyncStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSyncStats(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetSyncStats(
      ::grpc::CallbackServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetSyncStats(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StreamingSync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StreamingSync() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackBidiHandler< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StreamingSync(context); }));
    }
    ~ExperimentalWithCallbackMethod_StreamingSync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingSync(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* StreamingSync(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* StreamingSync(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SyncClock<ExperimentalWithCallbackMethod_GetSyncStats<ExperimentalWithCallbackMethod_StreamingSync<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SyncClock<ExperimentalWithCallbackMethod_GetSyncStats<ExperimentalWithCallbackMethod_StreamingSync<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SyncClock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SyncClock() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SyncClock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncClock(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetSyncStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSyncStats() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetSyncStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSyncStats(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamingSync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamingSync() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamingSync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingSync(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SyncClock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SyncClock() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SyncClock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncClock(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncClock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSyncStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSyncStats() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetSyncStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSyncStats(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSyncStats(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamingSync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamingSync() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamingSync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingSync(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingSync(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SyncClock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SyncClock() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SyncClock(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SyncClock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncClock(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SyncClock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SyncClock(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetSyncStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetSyncStats() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSyncStats(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetSyncStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSyncStats(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetSyncStats(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetSyncStats(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StreamingSync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StreamingSync() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StreamingSync(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_StreamingSync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingSync(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::openpni::distributed::timesync::ClockSyncResponse, ::openpni::distributed::timesync::ClockSyncRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingSync(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingSync(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SyncClock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SyncClock() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::openpni::distributed::timesync::ClockSyncRequest, ::openpni::distributed::timesync::ClockSyncResponse>* streamer) {
                       return this->StreamedSyncClock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SyncClock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SyncClock(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::ClockSyncRequest* /*request*/, ::openpni::distributed::timesync::ClockSyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSyncClock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::openpni::distributed::timesync::ClockSyncRequest,::openpni::distributed::timesync::ClockSyncResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSyncStats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSyncStats() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::openpni::distributed::timesync::EmptyRequest, ::openpni::distributed::timesync::AllClientStats>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::openpni::distributed::timesync::EmptyRequest, ::openpni::distributed::timesync::AllClientStats>* streamer) {
                       return this->StreamedGetSyncStats(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSyncStats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSyncStats(::grpc::ServerContext* /*context*/, const ::openpni::distributed::timesync::EmptyRequest* /*request*/, ::openpni::distributed::timesync::AllClientStats* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSyncStats(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::openpni::distributed::timesync::EmptyRequest,::openpni::distributed::timesync::AllClientStats>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SyncClock<WithStreamedUnaryMethod_GetSyncStats<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SyncClock<WithStreamedUnaryMethod_GetSyncStats<Service > > StreamedService;
};

}  // namespace timesync
}  // namespace distributed
}  // namespace openpni


#endif  // GRPC_timesync_2eproto__INCLUDED
