// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timesync.proto

#include "timesync.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_timesync_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ClientStats_timesync_2eproto;
namespace openpni {
namespace distributed {
namespace timesync {
class ClockSyncRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ClockSyncRequest> _instance;
} _ClockSyncRequest_default_instance_;
class ClockSyncResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ClockSyncResponse> _instance;
} _ClockSyncResponse_default_instance_;
class TimeSyncStatsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TimeSyncStats> _instance;
} _TimeSyncStats_default_instance_;
class AllClientStatsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AllClientStats> _instance;
} _AllClientStats_default_instance_;
class ClientStatsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ClientStats> _instance;
} _ClientStats_default_instance_;
class EmptyRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EmptyRequest> _instance;
} _EmptyRequest_default_instance_;
}  // namespace timesync
}  // namespace distributed
}  // namespace openpni
static void InitDefaultsscc_info_AllClientStats_timesync_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::timesync::_AllClientStats_default_instance_;
    new (ptr) ::openpni::distributed::timesync::AllClientStats();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::timesync::AllClientStats::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_AllClientStats_timesync_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_AllClientStats_timesync_2eproto}, {
      &scc_info_ClientStats_timesync_2eproto.base,}};

static void InitDefaultsscc_info_ClientStats_timesync_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::timesync::_ClientStats_default_instance_;
    new (ptr) ::openpni::distributed::timesync::ClientStats();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::timesync::ClientStats::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ClientStats_timesync_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ClientStats_timesync_2eproto}, {}};

static void InitDefaultsscc_info_ClockSyncRequest_timesync_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::timesync::_ClockSyncRequest_default_instance_;
    new (ptr) ::openpni::distributed::timesync::ClockSyncRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::timesync::ClockSyncRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ClockSyncRequest_timesync_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ClockSyncRequest_timesync_2eproto}, {}};

static void InitDefaultsscc_info_ClockSyncResponse_timesync_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::timesync::_ClockSyncResponse_default_instance_;
    new (ptr) ::openpni::distributed::timesync::ClockSyncResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::timesync::ClockSyncResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ClockSyncResponse_timesync_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ClockSyncResponse_timesync_2eproto}, {}};

static void InitDefaultsscc_info_EmptyRequest_timesync_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::timesync::_EmptyRequest_default_instance_;
    new (ptr) ::openpni::distributed::timesync::EmptyRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::timesync::EmptyRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EmptyRequest_timesync_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_EmptyRequest_timesync_2eproto}, {}};

static void InitDefaultsscc_info_TimeSyncStats_timesync_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openpni::distributed::timesync::_TimeSyncStats_default_instance_;
    new (ptr) ::openpni::distributed::timesync::TimeSyncStats();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openpni::distributed::timesync::TimeSyncStats::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TimeSyncStats_timesync_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TimeSyncStats_timesync_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_timesync_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_timesync_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_timesync_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_timesync_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncRequest, client_local_time_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncRequest, client_id_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncRequest, client_hostname_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncResponse, server_time_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncResponse, client_request_time_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncResponse, response_time_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncResponse, estimated_clock_offset_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClockSyncResponse, network_delay_estimate_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::TimeSyncStats, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::TimeSyncStats, client_id_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::TimeSyncStats, last_sync_time_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::TimeSyncStats, clock_offset_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::TimeSyncStats, clock_drift_rate_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::TimeSyncStats, sync_count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::AllClientStats, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::AllClientStats, clients_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, client_id_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, hostname_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, last_sync_time_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, clock_offset_ns_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, clock_drift_rate_),
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::ClientStats, sync_count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openpni::distributed::timesync::EmptyRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::openpni::distributed::timesync::ClockSyncRequest)},
  { 8, -1, sizeof(::openpni::distributed::timesync::ClockSyncResponse)},
  { 18, -1, sizeof(::openpni::distributed::timesync::TimeSyncStats)},
  { 28, -1, sizeof(::openpni::distributed::timesync::AllClientStats)},
  { 34, -1, sizeof(::openpni::distributed::timesync::ClientStats)},
  { 45, -1, sizeof(::openpni::distributed::timesync::EmptyRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::timesync::_ClockSyncRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::timesync::_ClockSyncResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::timesync::_TimeSyncStats_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::timesync::_AllClientStats_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::timesync::_ClientStats_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openpni::distributed::timesync::_EmptyRequest_default_instance_),
};

const char descriptor_table_protodef_timesync_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016timesync.proto\022\034openpni.distributed.ti"
  "mesync\"\\\n\020ClockSyncRequest\022\034\n\024client_loc"
  "al_time_ns\030\001 \001(\004\022\021\n\tclient_id\030\002 \001(\r\022\027\n\017c"
  "lient_hostname\030\003 \001(\t\"\253\001\n\021ClockSyncRespon"
  "se\022\026\n\016server_time_ns\030\001 \001(\004\022\036\n\026client_req"
  "uest_time_ns\030\002 \001(\004\022\030\n\020response_time_ns\030\003"
  " \001(\004\022!\n\031estimated_clock_offset_ns\030\004 \001(\003\022"
  "!\n\031network_delay_estimate_ms\030\005 \001(\002\"\201\001\n\rT"
  "imeSyncStats\022\021\n\tclient_id\030\001 \001(\r\022\026\n\016last_"
  "sync_time\030\002 \001(\004\022\027\n\017clock_offset_ns\030\003 \001(\003"
  "\022\030\n\020clock_drift_rate\030\004 \001(\002\022\022\n\nsync_count"
  "\030\005 \001(\r\"L\n\016AllClientStats\022:\n\007clients\030\001 \003("
  "\0132).openpni.distributed.timesync.ClientS"
  "tats\"\221\001\n\013ClientStats\022\021\n\tclient_id\030\001 \001(\r\022"
  "\020\n\010hostname\030\002 \001(\t\022\026\n\016last_sync_time\030\003 \001("
  "\004\022\027\n\017clock_offset_ns\030\004 \001(\003\022\030\n\020clock_drif"
  "t_rate\030\005 \001(\002\022\022\n\nsync_count\030\006 \001(\r\"\016\n\014Empt"
  "yRequest2\337\002\n\017TimeSyncService\022l\n\tSyncCloc"
  "k\022..openpni.distributed.timesync.ClockSy"
  "ncRequest\032/.openpni.distributed.timesync"
  ".ClockSyncResponse\022h\n\014GetSyncStats\022*.ope"
  "npni.distributed.timesync.EmptyRequest\032,"
  ".openpni.distributed.timesync.AllClientS"
  "tats\022t\n\rStreamingSync\022..openpni.distribu"
  "ted.timesync.ClockSyncRequest\032/.openpni."
  "distributed.timesync.ClockSyncResponse(\001"
  "0\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_timesync_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_timesync_2eproto_sccs[6] = {
  &scc_info_AllClientStats_timesync_2eproto.base,
  &scc_info_ClientStats_timesync_2eproto.base,
  &scc_info_ClockSyncRequest_timesync_2eproto.base,
  &scc_info_ClockSyncResponse_timesync_2eproto.base,
  &scc_info_EmptyRequest_timesync_2eproto.base,
  &scc_info_TimeSyncStats_timesync_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_timesync_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_timesync_2eproto = {
  false, false, descriptor_table_protodef_timesync_2eproto, "timesync.proto", 1050,
  &descriptor_table_timesync_2eproto_once, descriptor_table_timesync_2eproto_sccs, descriptor_table_timesync_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_timesync_2eproto::offsets,
  file_level_metadata_timesync_2eproto, 6, file_level_enum_descriptors_timesync_2eproto, file_level_service_descriptors_timesync_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_timesync_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_timesync_2eproto)), true);
namespace openpni {
namespace distributed {
namespace timesync {

// ===================================================================

void ClockSyncRequest::InitAsDefaultInstance() {
}
class ClockSyncRequest::_Internal {
 public:
};

ClockSyncRequest::ClockSyncRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.timesync.ClockSyncRequest)
}
ClockSyncRequest::ClockSyncRequest(const ClockSyncRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  client_hostname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_client_hostname().empty()) {
    client_hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_client_hostname(),
      GetArena());
  }
  ::memcpy(&client_local_time_ns_, &from.client_local_time_ns_,
    static_cast<size_t>(reinterpret_cast<char*>(&client_id_) -
    reinterpret_cast<char*>(&client_local_time_ns_)) + sizeof(client_id_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.timesync.ClockSyncRequest)
}

void ClockSyncRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ClockSyncRequest_timesync_2eproto.base);
  client_hostname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&client_local_time_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&client_id_) -
      reinterpret_cast<char*>(&client_local_time_ns_)) + sizeof(client_id_));
}

ClockSyncRequest::~ClockSyncRequest() {
  // @@protoc_insertion_point(destructor:openpni.distributed.timesync.ClockSyncRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ClockSyncRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  client_hostname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ClockSyncRequest::ArenaDtor(void* object) {
  ClockSyncRequest* _this = reinterpret_cast< ClockSyncRequest* >(object);
  (void)_this;
}
void ClockSyncRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ClockSyncRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClockSyncRequest& ClockSyncRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ClockSyncRequest_timesync_2eproto.base);
  return *internal_default_instance();
}


void ClockSyncRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.timesync.ClockSyncRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  client_hostname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&client_local_time_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&client_id_) -
      reinterpret_cast<char*>(&client_local_time_ns_)) + sizeof(client_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClockSyncRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 client_local_time_ns = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          client_local_time_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 client_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          client_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string client_hostname = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_client_hostname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.timesync.ClockSyncRequest.client_hostname"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ClockSyncRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.timesync.ClockSyncRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 client_local_time_ns = 1;
  if (this->client_local_time_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_client_local_time_ns(), target);
  }

  // uint32 client_id = 2;
  if (this->client_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_client_id(), target);
  }

  // string client_hostname = 3;
  if (this->client_hostname().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_hostname().data(), static_cast<int>(this->_internal_client_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.timesync.ClockSyncRequest.client_hostname");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_client_hostname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.timesync.ClockSyncRequest)
  return target;
}

size_t ClockSyncRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.timesync.ClockSyncRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_hostname = 3;
  if (this->client_hostname().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_hostname());
  }

  // uint64 client_local_time_ns = 1;
  if (this->client_local_time_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_client_local_time_ns());
  }

  // uint32 client_id = 2;
  if (this->client_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_client_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClockSyncRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.timesync.ClockSyncRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ClockSyncRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ClockSyncRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.timesync.ClockSyncRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.timesync.ClockSyncRequest)
    MergeFrom(*source);
  }
}

void ClockSyncRequest::MergeFrom(const ClockSyncRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.timesync.ClockSyncRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.client_hostname().size() > 0) {
    _internal_set_client_hostname(from._internal_client_hostname());
  }
  if (from.client_local_time_ns() != 0) {
    _internal_set_client_local_time_ns(from._internal_client_local_time_ns());
  }
  if (from.client_id() != 0) {
    _internal_set_client_id(from._internal_client_id());
  }
}

void ClockSyncRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.timesync.ClockSyncRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClockSyncRequest::CopyFrom(const ClockSyncRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.timesync.ClockSyncRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClockSyncRequest::IsInitialized() const {
  return true;
}

void ClockSyncRequest::InternalSwap(ClockSyncRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  client_hostname_.Swap(&other->client_hostname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClockSyncRequest, client_id_)
      + sizeof(ClockSyncRequest::client_id_)
      - PROTOBUF_FIELD_OFFSET(ClockSyncRequest, client_local_time_ns_)>(
          reinterpret_cast<char*>(&client_local_time_ns_),
          reinterpret_cast<char*>(&other->client_local_time_ns_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ClockSyncRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ClockSyncResponse::InitAsDefaultInstance() {
}
class ClockSyncResponse::_Internal {
 public:
};

ClockSyncResponse::ClockSyncResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.timesync.ClockSyncResponse)
}
ClockSyncResponse::ClockSyncResponse(const ClockSyncResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&server_time_ns_, &from.server_time_ns_,
    static_cast<size_t>(reinterpret_cast<char*>(&network_delay_estimate_ms_) -
    reinterpret_cast<char*>(&server_time_ns_)) + sizeof(network_delay_estimate_ms_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.timesync.ClockSyncResponse)
}

void ClockSyncResponse::SharedCtor() {
  ::memset(&server_time_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&network_delay_estimate_ms_) -
      reinterpret_cast<char*>(&server_time_ns_)) + sizeof(network_delay_estimate_ms_));
}

ClockSyncResponse::~ClockSyncResponse() {
  // @@protoc_insertion_point(destructor:openpni.distributed.timesync.ClockSyncResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ClockSyncResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ClockSyncResponse::ArenaDtor(void* object) {
  ClockSyncResponse* _this = reinterpret_cast< ClockSyncResponse* >(object);
  (void)_this;
}
void ClockSyncResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ClockSyncResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClockSyncResponse& ClockSyncResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ClockSyncResponse_timesync_2eproto.base);
  return *internal_default_instance();
}


void ClockSyncResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.timesync.ClockSyncResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&server_time_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&network_delay_estimate_ms_) -
      reinterpret_cast<char*>(&server_time_ns_)) + sizeof(network_delay_estimate_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClockSyncResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 server_time_ns = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          server_time_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 client_request_time_ns = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          client_request_time_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 response_time_ns = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          response_time_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 estimated_clock_offset_ns = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          estimated_clock_offset_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float network_delay_estimate_ms = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          network_delay_estimate_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ClockSyncResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.timesync.ClockSyncResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 server_time_ns = 1;
  if (this->server_time_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_server_time_ns(), target);
  }

  // uint64 client_request_time_ns = 2;
  if (this->client_request_time_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_client_request_time_ns(), target);
  }

  // uint64 response_time_ns = 3;
  if (this->response_time_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_response_time_ns(), target);
  }

  // int64 estimated_clock_offset_ns = 4;
  if (this->estimated_clock_offset_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_estimated_clock_offset_ns(), target);
  }

  // float network_delay_estimate_ms = 5;
  if (!(this->network_delay_estimate_ms() <= 0 && this->network_delay_estimate_ms() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_network_delay_estimate_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.timesync.ClockSyncResponse)
  return target;
}

size_t ClockSyncResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.timesync.ClockSyncResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 server_time_ns = 1;
  if (this->server_time_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_server_time_ns());
  }

  // uint64 client_request_time_ns = 2;
  if (this->client_request_time_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_client_request_time_ns());
  }

  // uint64 response_time_ns = 3;
  if (this->response_time_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_response_time_ns());
  }

  // int64 estimated_clock_offset_ns = 4;
  if (this->estimated_clock_offset_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_estimated_clock_offset_ns());
  }

  // float network_delay_estimate_ms = 5;
  if (!(this->network_delay_estimate_ms() <= 0 && this->network_delay_estimate_ms() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClockSyncResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.timesync.ClockSyncResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ClockSyncResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ClockSyncResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.timesync.ClockSyncResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.timesync.ClockSyncResponse)
    MergeFrom(*source);
  }
}

void ClockSyncResponse::MergeFrom(const ClockSyncResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.timesync.ClockSyncResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.server_time_ns() != 0) {
    _internal_set_server_time_ns(from._internal_server_time_ns());
  }
  if (from.client_request_time_ns() != 0) {
    _internal_set_client_request_time_ns(from._internal_client_request_time_ns());
  }
  if (from.response_time_ns() != 0) {
    _internal_set_response_time_ns(from._internal_response_time_ns());
  }
  if (from.estimated_clock_offset_ns() != 0) {
    _internal_set_estimated_clock_offset_ns(from._internal_estimated_clock_offset_ns());
  }
  if (!(from.network_delay_estimate_ms() <= 0 && from.network_delay_estimate_ms() >= 0)) {
    _internal_set_network_delay_estimate_ms(from._internal_network_delay_estimate_ms());
  }
}

void ClockSyncResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.timesync.ClockSyncResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClockSyncResponse::CopyFrom(const ClockSyncResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.timesync.ClockSyncResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClockSyncResponse::IsInitialized() const {
  return true;
}

void ClockSyncResponse::InternalSwap(ClockSyncResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClockSyncResponse, network_delay_estimate_ms_)
      + sizeof(ClockSyncResponse::network_delay_estimate_ms_)
      - PROTOBUF_FIELD_OFFSET(ClockSyncResponse, server_time_ns_)>(
          reinterpret_cast<char*>(&server_time_ns_),
          reinterpret_cast<char*>(&other->server_time_ns_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ClockSyncResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TimeSyncStats::InitAsDefaultInstance() {
}
class TimeSyncStats::_Internal {
 public:
};

TimeSyncStats::TimeSyncStats(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.timesync.TimeSyncStats)
}
TimeSyncStats::TimeSyncStats(const TimeSyncStats& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&last_sync_time_, &from.last_sync_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&sync_count_) -
    reinterpret_cast<char*>(&last_sync_time_)) + sizeof(sync_count_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.timesync.TimeSyncStats)
}

void TimeSyncStats::SharedCtor() {
  ::memset(&last_sync_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sync_count_) -
      reinterpret_cast<char*>(&last_sync_time_)) + sizeof(sync_count_));
}

TimeSyncStats::~TimeSyncStats() {
  // @@protoc_insertion_point(destructor:openpni.distributed.timesync.TimeSyncStats)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TimeSyncStats::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void TimeSyncStats::ArenaDtor(void* object) {
  TimeSyncStats* _this = reinterpret_cast< TimeSyncStats* >(object);
  (void)_this;
}
void TimeSyncStats::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TimeSyncStats::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TimeSyncStats& TimeSyncStats::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TimeSyncStats_timesync_2eproto.base);
  return *internal_default_instance();
}


void TimeSyncStats::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.timesync.TimeSyncStats)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&last_sync_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sync_count_) -
      reinterpret_cast<char*>(&last_sync_time_)) + sizeof(sync_count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TimeSyncStats::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          client_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 last_sync_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          last_sync_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 clock_offset_ns = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          clock_offset_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float clock_drift_rate = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          clock_drift_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // uint32 sync_count = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          sync_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TimeSyncStats::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.timesync.TimeSyncStats)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 client_id = 1;
  if (this->client_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_client_id(), target);
  }

  // uint64 last_sync_time = 2;
  if (this->last_sync_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_last_sync_time(), target);
  }

  // int64 clock_offset_ns = 3;
  if (this->clock_offset_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_clock_offset_ns(), target);
  }

  // float clock_drift_rate = 4;
  if (!(this->clock_drift_rate() <= 0 && this->clock_drift_rate() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_clock_drift_rate(), target);
  }

  // uint32 sync_count = 5;
  if (this->sync_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_sync_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.timesync.TimeSyncStats)
  return target;
}

size_t TimeSyncStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.timesync.TimeSyncStats)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 last_sync_time = 2;
  if (this->last_sync_time() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_last_sync_time());
  }

  // uint32 client_id = 1;
  if (this->client_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_client_id());
  }

  // float clock_drift_rate = 4;
  if (!(this->clock_drift_rate() <= 0 && this->clock_drift_rate() >= 0)) {
    total_size += 1 + 4;
  }

  // int64 clock_offset_ns = 3;
  if (this->clock_offset_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_clock_offset_ns());
  }

  // uint32 sync_count = 5;
  if (this->sync_count() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_sync_count());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TimeSyncStats::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.timesync.TimeSyncStats)
  GOOGLE_DCHECK_NE(&from, this);
  const TimeSyncStats* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TimeSyncStats>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.timesync.TimeSyncStats)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.timesync.TimeSyncStats)
    MergeFrom(*source);
  }
}

void TimeSyncStats::MergeFrom(const TimeSyncStats& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.timesync.TimeSyncStats)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.last_sync_time() != 0) {
    _internal_set_last_sync_time(from._internal_last_sync_time());
  }
  if (from.client_id() != 0) {
    _internal_set_client_id(from._internal_client_id());
  }
  if (!(from.clock_drift_rate() <= 0 && from.clock_drift_rate() >= 0)) {
    _internal_set_clock_drift_rate(from._internal_clock_drift_rate());
  }
  if (from.clock_offset_ns() != 0) {
    _internal_set_clock_offset_ns(from._internal_clock_offset_ns());
  }
  if (from.sync_count() != 0) {
    _internal_set_sync_count(from._internal_sync_count());
  }
}

void TimeSyncStats::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.timesync.TimeSyncStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TimeSyncStats::CopyFrom(const TimeSyncStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.timesync.TimeSyncStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TimeSyncStats::IsInitialized() const {
  return true;
}

void TimeSyncStats::InternalSwap(TimeSyncStats* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TimeSyncStats, sync_count_)
      + sizeof(TimeSyncStats::sync_count_)
      - PROTOBUF_FIELD_OFFSET(TimeSyncStats, last_sync_time_)>(
          reinterpret_cast<char*>(&last_sync_time_),
          reinterpret_cast<char*>(&other->last_sync_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TimeSyncStats::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AllClientStats::InitAsDefaultInstance() {
}
class AllClientStats::_Internal {
 public:
};

AllClientStats::AllClientStats(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  clients_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.timesync.AllClientStats)
}
AllClientStats::AllClientStats(const AllClientStats& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      clients_(from.clients_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.timesync.AllClientStats)
}

void AllClientStats::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AllClientStats_timesync_2eproto.base);
}

AllClientStats::~AllClientStats() {
  // @@protoc_insertion_point(destructor:openpni.distributed.timesync.AllClientStats)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AllClientStats::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void AllClientStats::ArenaDtor(void* object) {
  AllClientStats* _this = reinterpret_cast< AllClientStats* >(object);
  (void)_this;
}
void AllClientStats::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AllClientStats::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AllClientStats& AllClientStats::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AllClientStats_timesync_2eproto.base);
  return *internal_default_instance();
}


void AllClientStats::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.timesync.AllClientStats)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clients_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AllClientStats::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .openpni.distributed.timesync.ClientStats clients = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_clients(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AllClientStats::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.timesync.AllClientStats)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .openpni.distributed.timesync.ClientStats clients = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_clients_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_clients(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.timesync.AllClientStats)
  return target;
}

size_t AllClientStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.timesync.AllClientStats)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .openpni.distributed.timesync.ClientStats clients = 1;
  total_size += 1UL * this->_internal_clients_size();
  for (const auto& msg : this->clients_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AllClientStats::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.timesync.AllClientStats)
  GOOGLE_DCHECK_NE(&from, this);
  const AllClientStats* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AllClientStats>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.timesync.AllClientStats)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.timesync.AllClientStats)
    MergeFrom(*source);
  }
}

void AllClientStats::MergeFrom(const AllClientStats& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.timesync.AllClientStats)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  clients_.MergeFrom(from.clients_);
}

void AllClientStats::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.timesync.AllClientStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AllClientStats::CopyFrom(const AllClientStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.timesync.AllClientStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AllClientStats::IsInitialized() const {
  return true;
}

void AllClientStats::InternalSwap(AllClientStats* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  clients_.InternalSwap(&other->clients_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AllClientStats::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ClientStats::InitAsDefaultInstance() {
}
class ClientStats::_Internal {
 public:
};

ClientStats::ClientStats(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.timesync.ClientStats)
}
ClientStats::ClientStats(const ClientStats& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  hostname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_hostname().empty()) {
    hostname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_hostname(),
      GetArena());
  }
  ::memcpy(&last_sync_time_, &from.last_sync_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&sync_count_) -
    reinterpret_cast<char*>(&last_sync_time_)) + sizeof(sync_count_));
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.timesync.ClientStats)
}

void ClientStats::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ClientStats_timesync_2eproto.base);
  hostname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&last_sync_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sync_count_) -
      reinterpret_cast<char*>(&last_sync_time_)) + sizeof(sync_count_));
}

ClientStats::~ClientStats() {
  // @@protoc_insertion_point(destructor:openpni.distributed.timesync.ClientStats)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ClientStats::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  hostname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ClientStats::ArenaDtor(void* object) {
  ClientStats* _this = reinterpret_cast< ClientStats* >(object);
  (void)_this;
}
void ClientStats::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ClientStats::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClientStats& ClientStats::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ClientStats_timesync_2eproto.base);
  return *internal_default_instance();
}


void ClientStats::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.timesync.ClientStats)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hostname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&last_sync_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sync_count_) -
      reinterpret_cast<char*>(&last_sync_time_)) + sizeof(sync_count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClientStats::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          client_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string hostname = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_hostname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "openpni.distributed.timesync.ClientStats.hostname"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 last_sync_time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          last_sync_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 clock_offset_ns = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          clock_offset_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float clock_drift_rate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          clock_drift_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // uint32 sync_count = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          sync_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ClientStats::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.timesync.ClientStats)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 client_id = 1;
  if (this->client_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_client_id(), target);
  }

  // string hostname = 2;
  if (this->hostname().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hostname().data(), static_cast<int>(this->_internal_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "openpni.distributed.timesync.ClientStats.hostname");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_hostname(), target);
  }

  // uint64 last_sync_time = 3;
  if (this->last_sync_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_last_sync_time(), target);
  }

  // int64 clock_offset_ns = 4;
  if (this->clock_offset_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_clock_offset_ns(), target);
  }

  // float clock_drift_rate = 5;
  if (!(this->clock_drift_rate() <= 0 && this->clock_drift_rate() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_clock_drift_rate(), target);
  }

  // uint32 sync_count = 6;
  if (this->sync_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_sync_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.timesync.ClientStats)
  return target;
}

size_t ClientStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.timesync.ClientStats)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string hostname = 2;
  if (this->hostname().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hostname());
  }

  // uint64 last_sync_time = 3;
  if (this->last_sync_time() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_last_sync_time());
  }

  // uint32 client_id = 1;
  if (this->client_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_client_id());
  }

  // float clock_drift_rate = 5;
  if (!(this->clock_drift_rate() <= 0 && this->clock_drift_rate() >= 0)) {
    total_size += 1 + 4;
  }

  // int64 clock_offset_ns = 4;
  if (this->clock_offset_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_clock_offset_ns());
  }

  // uint32 sync_count = 6;
  if (this->sync_count() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_sync_count());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientStats::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.timesync.ClientStats)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientStats* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ClientStats>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.timesync.ClientStats)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.timesync.ClientStats)
    MergeFrom(*source);
  }
}

void ClientStats::MergeFrom(const ClientStats& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.timesync.ClientStats)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.hostname().size() > 0) {
    _internal_set_hostname(from._internal_hostname());
  }
  if (from.last_sync_time() != 0) {
    _internal_set_last_sync_time(from._internal_last_sync_time());
  }
  if (from.client_id() != 0) {
    _internal_set_client_id(from._internal_client_id());
  }
  if (!(from.clock_drift_rate() <= 0 && from.clock_drift_rate() >= 0)) {
    _internal_set_clock_drift_rate(from._internal_clock_drift_rate());
  }
  if (from.clock_offset_ns() != 0) {
    _internal_set_clock_offset_ns(from._internal_clock_offset_ns());
  }
  if (from.sync_count() != 0) {
    _internal_set_sync_count(from._internal_sync_count());
  }
}

void ClientStats::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.timesync.ClientStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientStats::CopyFrom(const ClientStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.timesync.ClientStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientStats::IsInitialized() const {
  return true;
}

void ClientStats::InternalSwap(ClientStats* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  hostname_.Swap(&other->hostname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClientStats, sync_count_)
      + sizeof(ClientStats::sync_count_)
      - PROTOBUF_FIELD_OFFSET(ClientStats, last_sync_time_)>(
          reinterpret_cast<char*>(&last_sync_time_),
          reinterpret_cast<char*>(&other->last_sync_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientStats::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EmptyRequest::InitAsDefaultInstance() {
}
class EmptyRequest::_Internal {
 public:
};

EmptyRequest::EmptyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openpni.distributed.timesync.EmptyRequest)
}
EmptyRequest::EmptyRequest(const EmptyRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:openpni.distributed.timesync.EmptyRequest)
}

void EmptyRequest::SharedCtor() {
}

EmptyRequest::~EmptyRequest() {
  // @@protoc_insertion_point(destructor:openpni.distributed.timesync.EmptyRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void EmptyRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void EmptyRequest::ArenaDtor(void* object) {
  EmptyRequest* _this = reinterpret_cast< EmptyRequest* >(object);
  (void)_this;
}
void EmptyRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EmptyRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EmptyRequest& EmptyRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EmptyRequest_timesync_2eproto.base);
  return *internal_default_instance();
}


void EmptyRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:openpni.distributed.timesync.EmptyRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EmptyRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EmptyRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openpni.distributed.timesync.EmptyRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openpni.distributed.timesync.EmptyRequest)
  return target;
}

size_t EmptyRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openpni.distributed.timesync.EmptyRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EmptyRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openpni.distributed.timesync.EmptyRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const EmptyRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EmptyRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openpni.distributed.timesync.EmptyRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openpni.distributed.timesync.EmptyRequest)
    MergeFrom(*source);
  }
}

void EmptyRequest::MergeFrom(const EmptyRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openpni.distributed.timesync.EmptyRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void EmptyRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openpni.distributed.timesync.EmptyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EmptyRequest::CopyFrom(const EmptyRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openpni.distributed.timesync.EmptyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EmptyRequest::IsInitialized() const {
  return true;
}

void EmptyRequest::InternalSwap(EmptyRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EmptyRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace timesync
}  // namespace distributed
}  // namespace openpni
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::openpni::distributed::timesync::ClockSyncRequest* Arena::CreateMaybeMessage< ::openpni::distributed::timesync::ClockSyncRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::timesync::ClockSyncRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::timesync::ClockSyncResponse* Arena::CreateMaybeMessage< ::openpni::distributed::timesync::ClockSyncResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::timesync::ClockSyncResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::timesync::TimeSyncStats* Arena::CreateMaybeMessage< ::openpni::distributed::timesync::TimeSyncStats >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::timesync::TimeSyncStats >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::timesync::AllClientStats* Arena::CreateMaybeMessage< ::openpni::distributed::timesync::AllClientStats >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::timesync::AllClientStats >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::timesync::ClientStats* Arena::CreateMaybeMessage< ::openpni::distributed::timesync::ClientStats >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::timesync::ClientStats >(arena);
}
template<> PROTOBUF_NOINLINE ::openpni::distributed::timesync::EmptyRequest* Arena::CreateMaybeMessage< ::openpni::distributed::timesync::EmptyRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openpni::distributed::timesync::EmptyRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
