#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${SCRIPT_DIR}/state"

STATE_FILES=()
PCI_ADDRS=()
RESTORE_DRIVER=""
CLEAR_HUGEPAGES=0
RESTORE_SYSTEM_STATE=0
DRY_RUN=0
ASSUME_YES=0

usage() {
  cat <<'EOF'
Usage:
  dpdk_rollback.sh [options]

Options:
  --state-file <path>              state file generated by dpdk_apply.sh (repeatable)
  --pci <domain:bus:slot.func>     pci addr if no state file is provided (repeatable)
  --restore-driver <name>          original kernel driver if no state file is provided
  --clear-hugepages                reset hugepages count to 0 for 2M and 1G
  --restore-system-state           restore hugepages/mount/vfio snapshot from first state file
  --yes                            do not ask for confirmation
  --dry-run                        print actions only
  --help                           print this help

Behavior:
  1. Prefer state-file mode for safer rollback.
  2. If --state-file is omitted, both --pci and --restore-driver are required.
EOF
}

log() {
  echo "[INFO] $*"
}

run_cmd() {
  if [[ "$#" -eq 0 ]]; then
    return 0
  fi
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    printf "[DRY-RUN]"
    for arg in "$@"; do
      printf " %q" "${arg}"
    done
    printf "\n"
    return 0
  fi
  "$@"
}

as_root() {
  if [[ "$#" -eq 0 ]]; then
    return 0
  fi
  if [[ "${EUID}" -eq 0 ]]; then
    run_cmd "$@"
  else
    run_cmd sudo "$@"
  fi
}

need_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "[ERROR] missing command: $cmd"
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --state-file)
      STATE_FILES+=("$2")
      shift 2
      ;;
    --pci)
      PCI_ADDRS+=("$2")
      shift 2
      ;;
    --restore-driver)
      RESTORE_DRIVER="$2"
      shift 2
      ;;
    --clear-hugepages)
      CLEAR_HUGEPAGES=1
      shift
      ;;
    --restore-system-state)
      RESTORE_SYSTEM_STATE=1
      shift
      ;;
    --yes)
      ASSUME_YES=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

need_cmd dpdk-devbind.py

ARG_PCI_ADDRS=("${PCI_ADDRS[@]}")
ARG_RESTORE_DRIVER="${RESTORE_DRIVER}"

if [[ "${#STATE_FILES[@]}" -eq 0 && "${#PCI_ADDRS[@]}" -eq 0 && -d "${STATE_DIR}" ]]; then
  LATEST_STATE="$(ls -1t "${STATE_DIR}"/*.env 2>/dev/null | head -n 1 || true)"
  if [[ -n "${LATEST_STATE}" ]]; then
    log "No --state-file/--pci provided, auto-select latest state: ${LATEST_STATE}"
    STATE_FILES+=("${LATEST_STATE}")
  fi
fi

ROLLBACK_PAIRS=()
RESTORE_HP_2M=""
RESTORE_HP_1G=""
RESTORE_MOUNT_PATH=""
RESTORE_MOUNT_EXISTED=""
RESTORE_VFIO_NOIOMMU=""

if [[ "${#STATE_FILES[@]}" -gt 0 ]]; then
  for sf in "${STATE_FILES[@]}"; do
    if [[ ! -f "${sf}" ]]; then
      echo "[ERROR] state file not found: ${sf}"
      exit 1
    fi
    # shellcheck disable=SC1090
    source "${sf}"
    if [[ -z "${PCI_ADDR:-}" || -z "${ORIG_DRIVER:-}" ]]; then
      echo "[ERROR] invalid state file: ${sf}"
      exit 1
    fi
    local_driver="${ARG_RESTORE_DRIVER:-${ORIG_DRIVER}}"
    ROLLBACK_PAIRS+=("${PCI_ADDR}:${local_driver}")

    if [[ -z "${RESTORE_HP_2M}" ]]; then
      RESTORE_HP_2M="${HP_2M_BEFORE:-}"
      RESTORE_HP_1G="${HP_1G_BEFORE:-}"
      RESTORE_MOUNT_PATH="${HUGEPAGES_MOUNT:-/dev/hugepages}"
      RESTORE_MOUNT_EXISTED="${HUGEPAGE_MOUNT_EXISTED:-}"
      RESTORE_VFIO_NOIOMMU="${VFIO_NOIOMMU_BEFORE:-}"
    fi
  done
else
  if [[ "${#PCI_ADDRS[@]}" -eq 0 || -z "${RESTORE_DRIVER}" ]]; then
    echo "[ERROR] missing rollback target. Provide --state-file(s) or (--pci and --restore-driver)."
    exit 1
  fi
  for p in "${PCI_ADDRS[@]}"; do
    ROLLBACK_PAIRS+=("${p}:${RESTORE_DRIVER}")
  done
fi

if [[ "${ASSUME_YES}" -ne 1 ]]; then
  echo "About to rollback:"
  echo "  ROLLBACK_TARGETS=${ROLLBACK_PAIRS[*]}"
  echo "  RESTORE_DRIVER_OVERRIDE=${RESTORE_DRIVER:-<from-state>}"
  echo "  CLEAR_HUGEPAGES=${CLEAR_HUGEPAGES}"
  echo "  RESTORE_SYSTEM_STATE=${RESTORE_SYSTEM_STATE}"
  echo
  read -r -p "Continue? [y/N]: " answer
  if [[ "${answer}" != "y" && "${answer}" != "Y" ]]; then
    echo "Canceled."
    exit 1
  fi
fi

for pair in "${ROLLBACK_PAIRS[@]}"; do
  pci="${pair%%:*}"
  drv="${pair#*:}"
  as_root dpdk-devbind.py "--bind=${drv}" "${pci}"
done

if [[ "${CLEAR_HUGEPAGES}" -eq 1 ]]; then
  if [[ -e /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages ]]; then
    as_root sh -c "echo 0 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
  fi
  if [[ -e /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages ]]; then
    as_root sh -c "echo 0 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages"
  fi
fi

if [[ "${RESTORE_SYSTEM_STATE}" -eq 1 ]]; then
  if [[ -n "${RESTORE_HP_2M}" && "${RESTORE_HP_2M}" != "unknown" ]]; then
    if [[ -e /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages ]]; then
      as_root sh -c "echo ${RESTORE_HP_2M} > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
    fi
  fi
  if [[ -n "${RESTORE_HP_1G}" && "${RESTORE_HP_1G}" != "unknown" ]]; then
    if [[ -e /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages ]]; then
      as_root sh -c "echo ${RESTORE_HP_1G} > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages"
    fi
  fi
  if [[ -n "${RESTORE_MOUNT_PATH}" && "${RESTORE_MOUNT_EXISTED}" == "0" ]]; then
    if mount | grep -q "on ${RESTORE_MOUNT_PATH} type hugetlbfs"; then
      as_root umount "${RESTORE_MOUNT_PATH}" || true
    fi
  fi
  if [[ -n "${RESTORE_VFIO_NOIOMMU}" && "${RESTORE_VFIO_NOIOMMU}" != "unknown" ]]; then
    as_root modprobe -r vfio || true
    as_root modprobe vfio "enable_unsafe_noiommu_mode=${RESTORE_VFIO_NOIOMMU}" || true
  fi
fi

log "Final status"
dpdk-devbind.py --status || true
if command -v dpdk-hugepages.py >/dev/null 2>&1; then
  dpdk-hugepages.py -s || true
fi

log "Rollback completed."
