#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${SCRIPT_DIR}/state"

STATE_FILE=""
PCI_ADDR=""
RESTORE_DRIVER=""
CLEAR_HUGEPAGES=0
DRY_RUN=0
ASSUME_YES=0

usage() {
  cat <<'EOF'
Usage:
  dpdk_rollback.sh [options]

Options:
  --state-file <path>              state file generated by dpdk_apply.sh
  --pci <domain:bus:slot.func>     pci addr if no state file is provided
  --restore-driver <name>          original kernel driver if no state file is provided
  --clear-hugepages                reset hugepages count to 0 for 2M and 1G
  --yes                            do not ask for confirmation
  --dry-run                        print actions only
  --help                           print this help

Behavior:
  1. Prefer state-file mode for safer rollback.
  2. If --state-file is omitted, both --pci and --restore-driver are required.
EOF
}

log() {
  echo "[INFO] $*"
}

run_cmd() {
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    echo "[DRY-RUN] $*"
  else
    eval "$*"
  fi
}

as_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    run_cmd "$*"
  else
    run_cmd "sudo $*"
  fi
}

need_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "[ERROR] missing command: $cmd"
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --state-file)
      STATE_FILE="$2"
      shift 2
      ;;
    --pci)
      PCI_ADDR="$2"
      shift 2
      ;;
    --restore-driver)
      RESTORE_DRIVER="$2"
      shift 2
      ;;
    --clear-hugepages)
      CLEAR_HUGEPAGES=1
      shift
      ;;
    --yes)
      ASSUME_YES=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

need_cmd dpdk-devbind.py

ARG_PCI_ADDR="${PCI_ADDR}"
ARG_RESTORE_DRIVER="${RESTORE_DRIVER}"

if [[ -n "${STATE_FILE}" ]]; then
  if [[ ! -f "${STATE_FILE}" ]]; then
    echo "[ERROR] state file not found: ${STATE_FILE}"
    exit 1
  fi
  # shellcheck disable=SC1090
  source "${STATE_FILE}"
  STATE_PCI_ADDR="${PCI_ADDR:-}"
  STATE_ORIG_DRIVER="${ORIG_DRIVER:-}"
  PCI_ADDR="${ARG_PCI_ADDR:-${STATE_PCI_ADDR}}"
  RESTORE_DRIVER="${ARG_RESTORE_DRIVER:-${STATE_ORIG_DRIVER}}"
else
  if [[ -z "${PCI_ADDR}" || -z "${RESTORE_DRIVER}" ]]; then
    if [[ -d "${STATE_DIR}" ]]; then
      LATEST_STATE="$(ls -1t "${STATE_DIR}"/*.env 2>/dev/null | head -n 1 || true)"
      if [[ -n "${LATEST_STATE}" ]]; then
        log "No --state-file provided, auto-select latest state: ${LATEST_STATE}"
        # shellcheck disable=SC1090
        source "${LATEST_STATE}"
        STATE_PCI_ADDR="${PCI_ADDR:-}"
        STATE_ORIG_DRIVER="${ORIG_DRIVER:-}"
        PCI_ADDR="${ARG_PCI_ADDR:-${STATE_PCI_ADDR}}"
        RESTORE_DRIVER="${ARG_RESTORE_DRIVER:-${STATE_ORIG_DRIVER}}"
      fi
    fi
  fi
fi

if [[ -z "${PCI_ADDR}" || -z "${RESTORE_DRIVER}" ]]; then
  echo "[ERROR] missing rollback target. Provide --state-file or (--pci and --restore-driver)."
  exit 1
fi

if [[ "${ASSUME_YES}" -ne 1 ]]; then
  echo "About to rollback:"
  echo "  PCI_ADDR=${PCI_ADDR}"
  echo "  RESTORE_DRIVER=${RESTORE_DRIVER}"
  echo "  CLEAR_HUGEPAGES=${CLEAR_HUGEPAGES}"
  echo
  read -r -p "Continue? [y/N]: " answer
  if [[ "${answer}" != "y" && "${answer}" != "Y" ]]; then
    echo "Canceled."
    exit 1
  fi
fi

as_root "dpdk-devbind.py --bind=${RESTORE_DRIVER} ${PCI_ADDR}"

if [[ "${CLEAR_HUGEPAGES}" -eq 1 ]]; then
  if [[ -e /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages ]]; then
    as_root "sh -c 'echo 0 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages'"
  fi
  if [[ -e /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages ]]; then
    as_root "sh -c 'echo 0 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages'"
  fi
fi

log "Final status"
dpdk-devbind.py --status || true
if command -v dpdk-hugepages.py >/dev/null 2>&1; then
  dpdk-hugepages.py -s || true
fi

log "Rollback completed."
